/**
 * Every committed figure recorded to a video file, in a browser.
 *
 * This is not part of `npm test` and it never will be. Encoding needs a
 * WebCodecs VideoEncoder, Node has none, and rasterising needs a canvas, which
 * Node has none of either. A browser has both, so the claim that a figure
 * becomes a file that plays is gated the way every claim about pixels in this
 * family of packages is: with a device in the loop.
 *
 * What runs in the browser is the built package itself, served over a local
 * address and loaded as modules, so the gate measures what a consumer installs
 * rather than a copy of it. The encoder is a bare name inside a dynamic import,
 * which a browser cannot resolve on its own, and the engine's two doors are
 * more, so the server rewrites each one to what is installed as it hands the
 * file over. An import map would do the same for the page and nothing for the
 * worker, since a map belongs to the realm that declared it. The encoder is
 * mapped to its own bundle rather than to its module tree, since that tree
 * imports `node:fs/promises` for the target that writes a file and a browser
 * refuses the whole graph for it.
 *
 * Each figure is recorded four ways: through the two-dimensional painter and off
 * a card, each of those in the page and again in a worker that has no document.
 * The card draws on its own canvas and its frames reach the encoder's canvas as
 * the pixels `painterGpu` reads back, so two recordings of one figure differ in
 * how a frame was painted and in where it ran, and in nothing else.
 *
 * The file is read back afterwards in Node, which needs no encoder: reading a
 * container apart is arithmetic, and only writing the pictures inside it needs
 * WebCodecs. So the gate says how many pictures the file holds rather than only
 * how many the recorder handed over.
 *
 * Run it with `npm run gate:record`. It writes into `recordings/`, which is not
 * committed: a video regenerated by a gate is an output, and the reading the
 * gate prints is what a session quotes.
 */
import { createServer } from 'node:http';
import { mkdirSync, readFileSync, writeFileSync, readdirSync } from 'node:fs';
import path from 'node:path';
import { chromium } from 'playwright';
import { ALL_FORMATS, FilePathSource, Input } from 'mediabunny';

const root = path.resolve(import.meta.dirname, '..');
const out = path.join(root, 'recordings');

const FPS = 30;
const WIDTH = 1080;
const HEIGHT = 600;

const TYPES = {
  '.js': 'text/javascript',
  '.mjs': 'text/javascript',
  '.json': 'application/json',
  '.html': 'text/html',
  '.map': 'application/json',
};

const page_html = `<!doctype html>
<meta charset="utf-8">
<canvas id="surface"></canvas>
<canvas id="card"></canvas>
`;

/** Where each bare name the built package imports is installed. */
const INSTALLED = {
  mediabunny: '/node_modules/mediabunny/dist/bundles/mediabunny.mjs',
  '@altpsyche/engine': '/node_modules/@altpsyche/engine/dist/index.js',
  '@altpsyche/engine/maths': '/node_modules/@altpsyche/engine/dist/scene/maths.js',
};

/** The built package with each bare name rewritten to the path it is installed
 * at, which is the one resolution a page and a worker both read. A name nothing
 * here maps is left as it was written, since the typesetter's imports are never
 * reached by a recording. */
function resolved(source) {
  return source.replace(/(from |import\()'([^']+)'/g, (whole, lead, name) =>
    INSTALLED[name] ? `${lead}'${INSTALLED[name]}'` : whole
  );
}

/** The repository over a local address, so the page loads the built package and
 * the installed encoder by path rather than by bare name. */
function serve() {
  const server = createServer((request, response) => {
    const asked = decodeURIComponent(new URL(request.url, 'http://localhost').pathname);
    // The page is served rather than set on the browser, since a page set from
    // outside has no origin and a module fetched from one is refused.
    if (asked === '/') {
      response.writeHead(200, { 'content-type': 'text/html' });
      response.end(page_html);
      return;
    }
    const file = path.join(root, asked);
    if (!file.startsWith(root)) {
      response.writeHead(403).end();
      return;
    }
    try {
      const type = TYPES[path.extname(file)] ?? 'text/plain';
      const built = asked.startsWith('/dist/') && asked.endsWith('.js');
      const body = built ? resolved(readFileSync(file, 'utf8')) : readFileSync(file);
      response.writeHead(200, { 'content-type': type });
      response.end(body);
    } catch {
      response.writeHead(404).end();
    }
  });
  return new Promise((resolve) => {
    server.listen(0, '127.0.0.1', () => resolve({ server, port: server.address().port }));
  });
}


/** The card every figure is drawn on, opened once. A canvas keeps the first
 * graphics context it is given for as long as it lives, so one canvas serving
 * every recording is what a renderer opened once buys. */
async function openCard(page, origin) {
  return page.evaluate(
    async ({ origin, width, height }) => {
      const { gpuSurface } = await import(`${origin}/dist/index.js`);
      const card = document.getElementById('card');
      card.width = width;
      card.height = height;
      window.surface = await gpuSurface(card, {
        clear: [1, 1, 1, 1],
        onRefused: (message) => {
          throw new Error(message);
        },
      });
      if (!window.surface) throw new Error('no backend drew the figure');
      return window.surface.backend;
    },
    { origin, width: WIDTH, height: HEIGHT }
  );
}

/** The worker every recording with no page runs in, opened once, with the card
 * it draws on opened inside it. */
async function openWorker(page, origin) {
  return page.evaluate(
    async ({ origin, width, height }) => {
      window.worker = new Worker(`${origin}/gates/record-worker.mjs`, { type: 'module' });
      // One question at a time, each answer matched to the question by an id, so
      // a reply never reaches the wrong waiting promise.
      window.ask = (request) =>
        new Promise((done, failed) => {
          const id = `${window.asked = (window.asked ?? 0) + 1}`;
          const hear = (event) => {
            if (event.data.id !== id) return;
            window.worker.removeEventListener('message', hear);
            if (event.data.error) failed(new Error(event.data.error));
            else done(event.data.answer);
          };
          window.worker.addEventListener('message', hear);
          window.worker.postMessage({ ...request, id });
        });
      return window.ask({ kind: 'open', width, height });
    },
    { origin, width: WIDTH, height: HEIGHT }
  );
}

/** One figure recorded in the worker, which paints and encodes with no document
 * anywhere in the call. */
async function recordInWorker(page, origin, name, through) {
  return page.evaluate(
    ({ origin, name, through, fps, width, height }) =>
      window.ask({ kind: 'record', origin, name, through, fps, width, height }),
    { origin, name, through, fps: FPS, width: WIDTH, height: HEIGHT }
  );
}

/** One figure recorded in the page, painted either by the two-dimensional
 * painter or off the card, which answers the bytes and what the walk counted. */
async function record(page, origin, name, through) {
  return page.evaluate(
    async ({ origin, name, fps, width, height, through }) => {
      const { readFigure, recordFigure, videoSink, colourFrom, frameTimesOf, painterGpu } =
        await import(`${origin}/dist/index.js`);
      const text = await (await fetch(`${origin}/demos/${name}.figure.json`)).text();
      const figure = readFigure(text);
      const canvas = document.getElementById('surface');
      canvas.width = width;
      canvas.height = height;
      const sink = await videoSink(canvas, { fps, format: 'mp4', codec: 'avc' });
      // A card's frame opens on the clear colour the surface was opened with and
      // its pixels replace the canvas, so a ground painted underneath them would
      // be covered rather than shown.
      const refused = new Set();
      let triangles = 0;
      const card = through === 'card';
      const painting = card
        ? {
            paint: painterGpu(window.surface, (drawn) => {
              for (const mark of drawn.refused) refused.add(mark);
              triangles = Math.max(triangles, drawn.triangles);
            }),
          }
        : { background: colourFrom('#ffffff') };
      const started = performance.now();
      const recording = await recordFigure(figure, sink, {
        fps,
        width,
        height,
        ...painting,
      });
      // The last frame read back off the canvas, so a recording of nothing is
      // told from a recording of the figure. An encoder writes a white file as
      // happily as a drawn one.
      const pixels = canvas.getContext('2d').getImageData(0, 0, width, height).data;
      let inked = 0;
      for (let at = 0; at < pixels.length; at += 4) {
        if (pixels[at] !== 255 || pixels[at + 1] !== 255 || pixels[at + 2] !== 255) inked += 1;
      }
      let binary = '';
      for (const byte of recording.output) binary += String.fromCharCode(byte);
      return {
        bytes: btoa(binary),
        frames: recording.frames,
        walked: frameTimesOf(figure, { fps }).length,
        seconds: recording.seconds,
        inked: inked / (width * height),
        took: Math.round(performance.now() - started),
        refused: [...refused],
        triangles,
        document: typeof document,
      };
    },
    { origin, name, fps: FPS, width: WIDTH, height: HEIGHT, through }
  );
}

/** What the written file holds, read back out of the container. Demuxing needs
 * no encoder, so this half runs in Node. */
async function inside(file) {
  const input = new Input({ source: new FilePathSource(file), formats: ALL_FORMATS });
  const track = await input.getPrimaryVideoTrack();
  const stats = await track.computePacketStats();
  return {
    packets: stats.packetCount,
    duration: await input.computeDuration(),
    size: `${track.displayWidth}x${track.displayHeight}`,
    codec: track.codec,
  };
}

const figures = readdirSync(path.join(root, 'demos'))
  .filter((file) => file.endsWith('.figure.json'))
  .map((file) => file.replace('.figure.json', ''))
  .sort();

const { server, port } = await serve();
const origin = `http://127.0.0.1:${port}`;
const browser = await chromium.launch();
const page = await browser.newPage();
page.on('console', (message) => {
  if (message.type() === 'error') console.error(`  page: ${message.text()}`);
});
await page.goto(`${origin}/`);
const backend = await openCard(page, origin);
const worker = await openWorker(page, origin);

// Where each recording runs and what paints it, which is the four a figure is
// recorded as.
const PASSES = [
  { where: 'page', through: 'canvas', suffix: '' },
  { where: 'page', through: 'card', suffix: '.card' },
  { where: 'worker', through: 'canvas', suffix: '.worker' },
  { where: 'worker', through: 'card', suffix: '.worker.card' },
];

mkdirSync(out, { recursive: true });
let failed = 0;
for (const name of figures) {
  for (const pass of PASSES) {
    const stem = `${name}${pass.suffix}`;
    try {
      const answer =
        pass.where === 'worker'
          ? await recordInWorker(page, origin, name, pass.through)
          : await record(page, origin, name, pass.through);
      const bytes = Buffer.from(answer.bytes, 'base64');
      const file = path.join(out, `${stem}.mp4`);
      writeFileSync(file, bytes);
      const held = await inside(file);
      const wanted = pass.where === 'worker' ? 'undefined' : 'object';
      const agrees =
        answer.frames === answer.walked &&
        held.packets === answer.frames &&
        answer.inked > 0 &&
        answer.refused.length === 0 &&
        answer.document === wanted;
      console.log(
        `${stem}.mp4 ${bytes.length} bytes, ${answer.frames} frames of ${answer.walked} walked, ` +
          `${held.packets} in the file, ${held.duration.toFixed(4)}s of ${held.size} ${held.codec}, ` +
          `${(answer.inked * 100).toFixed(1)}% of the last frame drawn, ${answer.took}ms, ` +
          `document is ${answer.document}` +
          (pass.through === 'card' ? `, ${answer.refused.length} marks refused on ${backend}` : '') +
          `, ${agrees ? 'the file holds the walk' : 'THE FILE DISAGREES WITH THE WALK'}`
      );
      if (!agrees) failed += 1;
    } catch (error) {
      failed += 1;
      console.error(`${stem} failed: ${error.message}`);
    }
  }
}

// A recording with no figure behind it, made twice so the settled one's first picture can be
// told from the unsettled one's.
const SETTLES = [30, 0];
const opened = {};
for (const settle of SETTLES) {
  const stem = `accumulate.worker${settle ? '.settled' : ''}`;
  try {
    const answer = await page.evaluate(
      (request) => window.ask({ kind: 'accumulate', ...request }),
      { fps: FPS, seconds: 1, settle, width: WIDTH, height: HEIGHT }
    );
    const bytes = Buffer.from(answer.bytes, 'base64');
    const file = path.join(out, `${stem}.mp4`);
    writeFileSync(file, bytes);
    const held = await inside(file);
    opened[settle] = answer.first;
    const agrees =
      answer.frames === answer.walked &&
      held.packets === answer.frames &&
      answer.filled === answer.frames + settle &&
      answer.document === 'undefined';
    console.log(
      `${stem}.mp4 ${bytes.length} bytes, ${answer.filled} filled with a settle of ${settle}, ` +
        `${answer.frames} frames of ${answer.walked} walked, ${held.packets} in the file, ` +
        `${held.duration.toFixed(4)}s of ${held.size} ${held.codec}, first picture ` +
        `${(answer.first * 100).toFixed(1)}% dark and last ${(answer.last * 100).toFixed(1)}%, ` +
        `${agrees ? 'the file holds the kept frames' : 'THE FILE DISAGREES WITH THE WALK'}`
    );
    if (!agrees) failed += 1;
  } catch (error) {
    failed += 1;
    console.error(`${stem} failed: ${error.message}`);
  }
}
if (opened[30] !== undefined && opened[0] !== undefined && !(opened[30] > opened[0])) {
  failed += 1;
  console.error('the settled recording opens no darker than the unsettled one');
}

await browser.close();
server.close();
const asked = figures.length * PASSES.length + SETTLES.length;
console.log(
  `${asked - failed} of ${asked} recordings written into ${out}, each figure through the ` +
    `two-dimensional painter and off a ${backend} card, in the page and again in a worker ` +
    `on ${worker.backend} whose document is ${worker.document}, and one fill with no figure ` +
    `settled and unsettled`
);
process.exit(failed === 0 ? 0 : 1);
