/**
 * Every committed figure recorded to a video file, in a browser.
 *
 * This is not part of `npm test` and it never will be. Encoding needs a
 * WebCodecs VideoEncoder, Node has none, and rasterising needs a canvas, which
 * Node has none of either. A browser has both, so the claim that a figure
 * becomes a file that plays is gated the way every claim about pixels in this
 * family of packages is: with a device in the loop.
 *
 * What runs in the page is the built package itself, served over a local
 * address and loaded as modules, so the gate measures what a consumer installs
 * rather than a copy of it. The encoder is a bare name inside a dynamic import,
 * which a browser cannot resolve on its own, and the engine's two doors are
 * more, so the page carries an import map pointing each at what is installed.
 * The encoder is mapped to its own bundle rather than to its module tree, since
 * that tree imports `node:fs/promises` for the target that writes a file and a
 * browser refuses the whole graph for it.
 *
 * Each figure is recorded twice, through the two-dimensional painter and off a
 * card, which is what holds a recording painted by either to the same walk. The
 * card draws on its own canvas and its frames reach the encoder's canvas as the
 * pixels `painterGpu` reads back, so the two recordings differ in how a frame was
 * painted and in nothing else.
 *
 * The file is read back afterwards in Node, which needs no encoder: reading a
 * container apart is arithmetic, and only writing the pictures inside it needs
 * WebCodecs. So the gate says how many pictures the file holds rather than only
 * how many the recorder handed over.
 *
 * Run it with `npm run gate:record`. It writes into `recordings/`, which is not
 * committed: a video regenerated by a gate is an output, and the reading the
 * gate prints is what a session quotes.
 */
import { createServer } from 'node:http';
import { mkdirSync, readFileSync, writeFileSync, readdirSync } from 'node:fs';
import path from 'node:path';
import { chromium } from 'playwright';
import { ALL_FORMATS, FilePathSource, Input } from 'mediabunny';

const root = path.resolve(import.meta.dirname, '..');
const out = path.join(root, 'recordings');

const FPS = 30;
const WIDTH = 1080;
const HEIGHT = 600;

const TYPES = {
  '.js': 'text/javascript',
  '.mjs': 'text/javascript',
  '.json': 'application/json',
  '.html': 'text/html',
  '.map': 'application/json',
};

const page_html = `<!doctype html>
<meta charset="utf-8">
<script type="importmap">
{"imports": {
  "mediabunny": "/node_modules/mediabunny/dist/bundles/mediabunny.mjs",
  "@altpsyche/engine": "/node_modules/@altpsyche/engine/dist/index.js",
  "@altpsyche/engine/maths": "/node_modules/@altpsyche/engine/dist/scene/maths.js"
}}
</script>
<canvas id="surface"></canvas>
<canvas id="card"></canvas>
`;

/** The repository over a local address, so the page loads the built package and
 * the installed encoder by path rather than by bare name. */
function serve() {
  const server = createServer((request, response) => {
    const asked = decodeURIComponent(new URL(request.url, 'http://localhost').pathname);
    // The page is served rather than set on the browser, since a page set from
    // outside has no origin and a module fetched from one is refused.
    if (asked === '/') {
      response.writeHead(200, { 'content-type': 'text/html' });
      response.end(page_html);
      return;
    }
    const file = path.join(root, asked);
    if (!file.startsWith(root)) {
      response.writeHead(403).end();
      return;
    }
    try {
      const body = readFileSync(file);
      response.writeHead(200, { 'content-type': TYPES[path.extname(file)] ?? 'text/plain' });
      response.end(body);
    } catch {
      response.writeHead(404).end();
    }
  });
  return new Promise((resolve) => {
    server.listen(0, '127.0.0.1', () => resolve({ server, port: server.address().port }));
  });
}


/** The card every figure is drawn on, opened once. A canvas keeps the first
 * graphics context it is given for as long as it lives, so one canvas serving
 * every recording is what a renderer opened once buys. */
async function openCard(page, origin) {
  return page.evaluate(
    async ({ origin, width, height }) => {
      const { gpuSurface } = await import(`${origin}/dist/index.js`);
      const card = document.getElementById('card');
      card.width = width;
      card.height = height;
      window.surface = await gpuSurface(card, {
        clear: [1, 1, 1, 1],
        onRefused: (message) => {
          throw new Error(message);
        },
      });
      if (!window.surface) throw new Error('no backend drew the figure');
      return window.surface.backend;
    },
    { origin, width: WIDTH, height: HEIGHT }
  );
}

/** One figure recorded in the page, painted either by the two-dimensional
 * painter or off the card, which answers the bytes and what the walk counted. */
async function record(page, origin, name, through) {
  return page.evaluate(
    async ({ origin, name, fps, width, height, through }) => {
      const { readFigure, recordFigure, videoSink, colourFrom, frameTimesOf, painterGpu } =
        await import(`${origin}/dist/index.js`);
      const text = await (await fetch(`${origin}/demos/${name}.figure.json`)).text();
      const figure = readFigure(text);
      const canvas = document.getElementById('surface');
      canvas.width = width;
      canvas.height = height;
      const sink = await videoSink(canvas, { fps, format: 'mp4', codec: 'avc' });
      // A card's frame opens on the clear colour the surface was opened with and
      // its pixels replace the canvas, so a ground painted underneath them would
      // be covered rather than shown.
      const refused = new Set();
      let triangles = 0;
      const card = through === 'card';
      const painting = card
        ? {
            paint: painterGpu(window.surface, (drawn) => {
              for (const mark of drawn.refused) refused.add(mark);
              triangles = Math.max(triangles, drawn.triangles);
            }),
          }
        : { background: colourFrom('#ffffff') };
      const started = performance.now();
      const recording = await recordFigure(figure, sink, {
        fps,
        width,
        height,
        ...painting,
      });
      // The last frame read back off the canvas, so a recording of nothing is
      // told from a recording of the figure. An encoder writes a white file as
      // happily as a drawn one.
      const pixels = canvas.getContext('2d').getImageData(0, 0, width, height).data;
      let inked = 0;
      for (let at = 0; at < pixels.length; at += 4) {
        if (pixels[at] !== 255 || pixels[at + 1] !== 255 || pixels[at + 2] !== 255) inked += 1;
      }
      let binary = '';
      for (const byte of recording.output) binary += String.fromCharCode(byte);
      return {
        bytes: btoa(binary),
        frames: recording.frames,
        walked: frameTimesOf(figure, { fps }).length,
        seconds: recording.seconds,
        inked: inked / (width * height),
        took: Math.round(performance.now() - started),
        refused: [...refused],
        triangles,
      };
    },
    { origin, name, fps: FPS, width: WIDTH, height: HEIGHT, through }
  );
}

/** What the written file holds, read back out of the container. Demuxing needs
 * no encoder, so this half runs in Node. */
async function inside(file) {
  const input = new Input({ source: new FilePathSource(file), formats: ALL_FORMATS });
  const track = await input.getPrimaryVideoTrack();
  const stats = await track.computePacketStats();
  return {
    packets: stats.packetCount,
    duration: await input.computeDuration(),
    size: `${track.displayWidth}x${track.displayHeight}`,
    codec: track.codec,
  };
}

const figures = readdirSync(path.join(root, 'demos'))
  .filter((file) => file.endsWith('.figure.json'))
  .map((file) => file.replace('.figure.json', ''))
  .sort();

const { server, port } = await serve();
const origin = `http://127.0.0.1:${port}`;
const browser = await chromium.launch();
const page = await browser.newPage();
page.on('console', (message) => {
  if (message.type() === 'error') console.error(`  page: ${message.text()}`);
});
await page.goto(`${origin}/`);
const backend = await openCard(page, origin);

mkdirSync(out, { recursive: true });
let failed = 0;
for (const name of figures) {
  for (const through of ['canvas', 'card']) {
    const stem = through === 'card' ? `${name}.card` : name;
    try {
      const answer = await record(page, origin, name, through);
      const bytes = Buffer.from(answer.bytes, 'base64');
      const file = path.join(out, `${stem}.mp4`);
      writeFileSync(file, bytes);
      const held = await inside(file);
      const agrees =
        answer.frames === answer.walked &&
        held.packets === answer.frames &&
        answer.inked > 0 &&
        answer.refused.length === 0;
      console.log(
        `${stem}.mp4 ${bytes.length} bytes, ${answer.frames} frames of ${answer.walked} walked, ` +
          `${held.packets} in the file, ${held.duration.toFixed(4)}s of ${held.size} ${held.codec}, ` +
          `${(answer.inked * 100).toFixed(1)}% of the last frame drawn, ${answer.took}ms` +
          (through === 'card'
            ? `, ${answer.refused.length} marks refused on ${backend}`
            : '') +
          `, ${agrees ? 'the file holds the walk' : 'THE FILE DISAGREES WITH THE WALK'}`
      );
      if (!agrees) failed += 1;
    } catch (error) {
      failed += 1;
      console.error(`${stem} failed: ${error.message}`);
    }
  }
}

await browser.close();
server.close();
console.log(
  `${figures.length * 2 - failed} of ${figures.length * 2} recordings written into ${out}, ` +
    `each figure through the two-dimensional painter and off a ${backend} card`
);
process.exit(failed === 0 ? 0 : 1);
