/**
 * The shipped typeface as the bytes a font reader parses, written by
 * `font/build.mjs` and not by hand.
 *
 * A font arrives as a module rather than as a file beside the code because a file
 * is reached by a path, and a path is a different thing in Node, behind a bundler
 * and in a browser with neither. An import is the same thing everywhere. The
 * module is loaded by the call that needs it, so a consumer who never draws a
 * label never fetches these bytes.
 *
 * Noto Sans, subset to Latin-1 and the punctuation a figure writes, under the SIL
 * Open Font License 1.1. The licence text ships beside the generator.
 */

/** The subset as base64, which is what a module can carry and a byte array
 * cannot. */
const ENCODED =
  'AAEAAAAKAIAAAwAgT1MvMmlSAAwAADiEAAAAYGNtYXAiwURFAAA45AAAAFRnbHlmnGFkDwAAAKwAADKMaGVhZCiD2/4AADT0' +
  'AAAANmhoZWEMsww8AAA4YAAAACRobXR4ru8n0QAANSwAAAM0bG9jYaQLsakAADNYAAABnG1heHAA8AFsAAAzOAAAACBuYW1l' +
  'Km9DIQAAOTgAAAH8cG9zdP+fADIAADs0AAAAIAACAF4AAAH5AsoAAwAHAAAzESERJSERIV4Bm/6YATX+ywLK/TYzAmQAAgBI' +
  '//IAxALKAAMADwAANyMDMwM0NjMyFhUUBiMiJqM5GWt0JBoZJSUZGiTJAgH9bCUeHiUkICAAAAIAQQHIAVcCygADAAcAABMD' +
  'IwMhAyMDoBQ3FAEWFDcUAsr+/gEC/v4BAgAAAgAZAAACbALKABsAHwAAAQczFSMHIzcjByM3IzUzNyM1MzczBzM3MwczFQUz' +
  'NyMB4B+JlilHKY8nRiZ+iyCGkihIKJAoRSh//n+PH48BtKBD0dHR0UOgQtTU1NRCoKAAAwA+/8YCBAL3ACIAKQAwAAA3JiYn' +
  'NRYWFzUmJjU0Njc1MxUWFhcHJiYnFR4CFRQGBxUjEQYGFRQWFxM2NjU0Jif9N2ggImozY1xnWEA1VyQbIE0oQlgtaF9ANjMt' +
  'PEA7NjBBMQERD1UQGAHKG1JHSlQFWFcBFQ9KDRMDyRMrPzJGVwpvAowEKiEoKw/+4gYrIiYnEAAABQAx//YDDgLUAAsADwAZ' +
  'ACUALwAAEzIWFRQGIyImNTQ2BQEjAQUiBhUUFjMyNTQFMhYVFAYjIiY1NDYXIgYVFBYzMjU0w0pMSU1HS0YCFf50TQGM/oQm' +
  'IyMmTQFoSU1JTUdLRkwmIyMmTQLUdWpqd3dqanUK/TYCyjRRUFBSoqHgdWpqd3dqanU/UFBRUaKgAAADADX/9gLaAtUAHwAr' +
  'ADUAAAEyFhUUBgcXNjY3MwYGBxcjJwYGIyImNTQ2NyYmNTQ2FyIGFRQWFzY2NTQmAwYGFRQWMzI2NwEwUF1RPsEaIQtZEDAm' +
  'kndXL3RTZ3pTRyA3Y1IqNSYkOzMwUjY9Sj5AXB8C1VFJP1gkuh9RL0BuKY5UKjRmXk1dKCRSN0pSSCwnJD0lIj0oJC7+yCBC' +
  'NjdCKh0AAAEAQQHIAKACygADAAATAyMDoBQ3FALK/v4BAgABACj/YgEOAsoADQAAEzQ2NzMGBhUUFhcjJiYoR0xTRkdHRVJM' +
  'RwESeuNbXuJ3dN9eWN8AAQAe/2IBBALKAA0AAAEUBgcjNjY1NCYnMxYWAQRHTFJFR0dGU0xHARJ531he33R34l5b4wAAAQAp' +
  'ATYB/AL4AA4AAAEHNxcHFwcnByc3JzcXJwFCFMAOuHdWVU1ZdbYOvhUC+MA2XA+eL6+vL54PXDbAAAABADIAbwIIAlMACwAA' +
  'ATMVIxUjNSM1MzUzAUHHx0jHx0gBhEfOzkfPAAABACn/fwDAAHQACAAANwYGByM2NjczwA0xGEEOHQdeaTV/NjmINAAAAQAo' +
  'AOUBGgEzAAMAADc1MxUo8uVOTgAAAQBI//IAxAB5AAsAADc0NjMyFhUUBiMiJkgkGRolJRoZJDYlHh4lJCAgAAABAAoAAAFq' +
  'AsoAAwAAAQEjAQFq/vZWAQoCyv02AsoAAAIAMf/2AgsC1QANABkAAAEUBgYjIiY1NDY2MzIWBRQWMzI2NTQmIyIGAgswaFZ5' +
  'cy9oVXh2/n5DUVBFRVBRQwFmc6VYw610pFfBrpOSkZSSkpIAAAEAWQAAAWMCygAMAAAhIxE0NjcGBgcHJzczAWNWAgIQGhRM' +
  'LsFJAfMrNBwQFhE+O5YAAQAwAAACCALUABsAACEhNTc+AjU0JiMiBgcnNjYzMhYVFAYGBwcVIQII/ii7NkomRjg0TykvKm1E' +
  'ZHQuUjeVAWlJvTZUUTA7PSQgOyMxZVk4Yl82kwQAAAEALf/2AgMC1AAqAAABFAYHFRYWFRQGBiMiJic1FhYzMjY1NCYjIzUz' +
  'MjY1NCYjIgYHJzY2MzIWAe1QRFZUOnlfOGAsLWgwYFVpX0VGWFtGPDpSKCwmcUhwbQIjSFUOBApYRz5hNhEWUhYZS0JDO0tK' +
  'PTQ5Iho8HixkAAACABUAAAIoAs4ACgAUAAAlIxUjNSE1ATMRMyc0NjcjBgYHAyECKGhV/qoBUFtovQQBBAgYC9YBAKKioksB' +
  '4f4j4TRJIRMsD/7PAAEAP//2AgMCygAeAAABMhYVFAYjIiYnNRYWMzI2NTQmIyIGBycTIRUhBzY2ARNugo1+N2EhJGcvT2FW' +
  'XRxIFiwbAWb+5REROgG2bmRvfxQTUxYZS09GSwoFHAFRUM8DCAAAAgA3//YCDQLUAB4ALAAAEzQ+AjMyFhcVJiYjIg4CBzM2' +
  'NjMyFhUUBiMiJiYXMjY1NCYjIgYGFRQWFjcbR4BlFTMQEi0XRVw1GAMGF1JAXXJ7aERuQfI/TkVFL0YnIkQBMU2VeUgEBUsG' +
  'Bi5QaDsjMXFocIBEjIZRVURQJzwgK1U3AAEALAAAAgsCygAGAAAzASE1IRUBiAEl/n8B3/7eAnpQRP16AAMAMf/2AgoC1AAb' +
  'ACgANQAAATIWFRQGBgceAhUUBiMiJjU0NjY3JiY1NDY2FyIGFRQWFhc2NjU0JgMUFjMyNjU0JicnBgYBHV54JT4lLEgrf2tz' +
  'fClEJzRJOGA8N0cjPCQ0R0bPSk1JTVJEEEJFAtRYUytAMRMVNUYxWmllWzFINBIeVUI3SyhHNTIlMiMQFj42MjX+KDRFRTc0' +
  'RRoGHEkAAAIAMv/2AggC1AAeACwAAAEUDgIjIiYnNRYzMj4CNyMGBiMiJjU0NjYzMhYWJyIGFRQWMzI2NjU0JiYCCBtHgWUU' +
  'NREnMUZbNhgCBhZTQVxxOWZFRG5A8j5PQ0YwRiciRAGZTZV5SAUFSw0uT2k6IjFxZ0tsOkWLhlJURU8nPCArVDgAAAIASP/y' +
  'AMQCJgALABcAABM0NjMyFhUUBiMiJhE0NjMyFhUUBiMiJkgkGRolJRoZJCQZGiUlGhkkAeImHh4mJCAg/nglHh4lJCAgAAAC' +
  'AB//fwDCAiYACwAVAAATNDYzMhYVFAYjIiYTBgYHIz4CNzNGJBkaJSUaGSRxDTEYQgoTEQVeAeImHh4mJCAg/qs0gTUmV1Uj' +
  'AAEAMgB0AgkCYAAGAAAlJTUlFQUFAgn+KQHX/ocBeXTPMutOsp4AAgA4ANkCAgHnAAMABwAAEzUhFQU1IRU4Acr+NgHKAaBH' +
  'R8dHRwABADIAdAIJAmAABgAANyUlNQUVBTIBef6HAdf+KcKds07rMs8AAAIADP/yAZgC1AAfACsAADc0NjY3PgI1NCYjIgYH' +
  'JzY2MzIWFRQGBgcOAhUVIwc0NjMyFhUUBiMiJowPJSAnKxI+OzFMIx8oYTxfaB01JCEjDEYXIxsZJCQZGyPkJjcyGyEsKh4w' +
  'NBkRRhUcXlEtPzUeHCopHRGTJR4eJSQgIAAAAgA6/6cDSQLKAD8ATQAAARQOAiMiJicjBgYjIiY1NDY2MzIWFwcGFBUUFjMy' +
  'NjY1NCYmIyIGBhUUFjMyNjcVBgYjIiYmNTQ+AjMyFhYFFBYzMjY3NyYmIyIGBgNJFSxALC41BgUSRjVMUzRfQSxVGAoBJRkf' +
  'KxdLg1NynVGckz1vKytrQXaoWTpunWNool3+BzMrODEEBg0oFTE8GgFlLlhHKzUiJTJmVEJlOg8JyxIPAzQiM1UzXYFEXqVq' +
  'lJ4bEEQSF1ildF2fdUFWoK9AOlRDfQQGMEsAAgAAAAACfgLNAAcAEQAAISchByMBMwEBLgInBgYHBzMCIVb+5VVbARdRARb+' +
  '4gMODQQHEgZR4t3dAs39MwIFCCotDB87EdgAAwBhAAACVALKABAAGQAiAAABMhYVFAYHFR4CFRQGIyMREzI2NTQmIyMVFREz' +
  'MjY1NCYjAS2GiUZCLUkqhXP73lxEU1t2kF9KTWMCyk9iP1MMBQcmRjhhagLK/tA7Ojsz40v+/Uo8OEUAAAEAPf/2AlkC1AAa' +
  'AAABIgYVFBYzMjY3FQYGIyImJjU0NjYzMhcHJiYBk3OEe3svVCgoVTttkklPmm5xVCQhUQKFmoaFmxAMTg8OWqZwbKVdKkwP' +
  'GAAAAgBhAAACnQLKAAkAEQAAARQGIyMRMzIWFgc0JiMjETMgAp3FsMfcbJ5WX42BdWEBIgFstbcCylCbdo+F/dAAAAEAYQAA' +
  'AfACygALAAAhIREhFSEVIRUhFSEB8P5xAY/+ywEj/t0BNQLKT99O/wABAGEAAAHwAsoACQAAMyMRIRUhFSEVIbtaAY/+ywEi' +
  '/t4Cyk/9TwAAAQA9//YCjgLUACAAAAEzEQYGIyImJjU0NjYzMhYXByYmIyIGFRQWFjMyNjc1IwGX9zp2S2+YT1ildTxrLiIm' +
  'XzOAjzd2YC9CG50Bef6iExJZpXFwpFsWFE4RGJqGVYNJCgfUAAEAYQAAAoMCygALAAAhIxEhESMRMxEhETMCg1r+klpaAW5a' +
  'AU3+swLK/tIBLgABACgAAAEqAsoACwAAISE1NxEnNSEVBxEXASr+/lRUAQJUVDQTAjsUNDQU/cUTAAAB/7L/QgC2AsoAEAAA' +
  'ByImJzUWFjMyNjY1ETMRFAYEGCQOECQUGS0cWma+BwZMBAYUMi0Cxv1BZ2IAAQBhAAACawLKAA4AACEjAwcRIxEzETY2Nzcz' +
  'AQJrav1JWloePh/Baf7lAVVA/usCyv6gIkQi2P7JAAEAYQAAAfMCygAFAAAzETMRIRVhWgE4Asr9hlAAAAEAYQAAAyoCygAV' +
  'AAAhAyMWFhURIxEzEzMTMxEjETQ2NyMDAZzrBAMEU4XcBOCEWQUCBO4Cch9pOf5PAsr9twJJ/TYBtzRmIP2PAAABAGEAAAKX' +
  'AsoAEgAAISMBIxYWFREjETMBMy4CNREzApdp/oIEAgZTaAF9BAEDA1QCUSNoN/5xAsr9sRBATCABkwACAD3/9gLQAtUADwAb' +
  'AAABFAYGIyImJjU0NjYzMhYWBRQWMzI2NTQmIyIGAtBLkmxvk0hIk3Brkkv9zHJ5enBweXlzAWZvpVxcpm9upFxbpW+Hm5uH' +
  'h5mZAAACAGEAAAIqAsoACwAUAAABMhYVFAYGIyMRIxEXIxEzMjY1NCYBHoyANX1rUlq1W0hmZFgCym5kO2dA/uoCyk3+5kJP' +
  'RUQAAgA9/1YC0ALVABQAIAAAARQGBxcjJyIGIyImJjU0NjYzMhYWBRQWMzI2NTQmIyIGAtBpZ6uBigYNBm+TSEiTcGuSS/3M' +
  'cnl6cHB5eXMBZoO4I7KhAVymb26kXFulb4ebm4eHmZkAAgBhAAACXwLKAA4AFwAAATIWFRQGBgcTIwMjESMRFyMRMzI2NTQm' +
  'ASaFfypBJMRprY5awGZrV1BUAsplZjlMLQ3+wAEn/tkCyk7+90VDRjsAAAEAM//2AfYC1AApAAAlFAYjIiYnNRYWMzI2NTQm' +
  'JicmJjU0NjYzMhYXByYmIyIGFRQWFhceAgH2inU8ZiIkazlQUR5JQVtdOmdDO2IoHCVXL0NEHkQ6P1ctv19qEhBWEBo+NSMw' +
  'KRchYFM5USwWEk0QFjkvJDAmFhc1SgABAAoAAAIhAsoABwAAISMRIzUhFSMBQ1rfAhfeAntPTwAAAQBa//YCgALKABIAACUU' +
  'BgYjIiY1ETMRFBYzMjY1ETMCgDx7X4WLWl1eYVdZ/Ep3RZF3Acz+MVdgZ1EBzgABAAAAAAJYAsoADAAAAQMjAzMTFhYXNjY3' +
  'EwJY/1r/XqEQFgcHFhCgAsr9NgLK/jYsTSMjTi0ByAAAAQAMAAADlQLKAB8AAAEDIwMuAicGBgcDIwMzExYWFzY2NxMzExYW' +
  'FzY2NxMDlb5biwgQCgIBEw6HW71ebwwRBQUUDX5dgw4UBQUSDG4Cyv02AdQdOi0JDVUu/i8Cyv5MLlYmJ1wsAa/+Ti5bIyVX' +
  'LwGzAAABAAQAAAJGAsoACwAAISMDAyMTAzMTEzMDAkZmvcBf7d5kr7Bf3QE2/soBdAFW/ugBGP6sAAABAAAAAAI2AsoACAAA' +
  'ARMzAxEjEQMzARu6Ye5a7mIBawFf/kv+6wERAbkAAAEAJgAAAhUCygAJAAAhITUBITUhFQEhAhX+EQF4/pQB2f6IAYJEAjZQ' +
  'RP3KAAABAFD/YgEwAsoABwAABSMRMxUjETMBMODgioqeA2hI/SgAAQAKAAABawLKAAMAABMBIwFgAQtX/vYCyv02AsoAAQAZ' +
  '/2IA+QLKAAcAABczESM1MxEjGYqK4OBWAthI/JgAAAEAJgELAhYCzwAGAAATEzMTIwMDJtQy6k60oAELAcT+PAFn/pkAAf/+' +
  '/2YBvv+mAAMAAAUhNSEBvv5AAcCaQAABACgCXgDxAv4ACwAAEx4CFxUjLgInNZELISUPOxc6MQwC/hY3NBMMEjk5EgoAAgAu' +
  '//YB4AIhABsAJgAAATIWFREjJyMGBiMiJjU0Njc3NTQmIyIGByc2NhMGBhUUFjMyNjU1ASBiXkARBCNNRElgfoNbOjUqTCEb' +
  'I2BOZE03K0RaAiFWXv6TTCwqTVJQVwQDIEM0GRBCExv+4gQ4My0qS04wAAIAVf/2AjAC+AAVACEAABMUBgczNjYzMhYVFAYj' +
  'IiYnIwcjETMTIgYVFRQWMzI2NTStAwIFF1A/ZHl6Yz9QFwcSP1iXVUJBWEhHAj8iOxEiLouKiowuIEQC+P7gYmcEY2lqZMsA' +
  'AAEAN//2Ab8CIgAaAAAFIiYmNTQ2NjMyFhcHJiYjIhUUFjMyNjcVBgYBLEdvP0JxSClMGBsYQByeTUwsQxwbQQo6el9jfDoR' +
  'DEkJEMthZxINTg4PAAIAN//2AhIC+AAVACIAAAUiJjU0NjMyFhczJiY1NTMRIycjBgYnMjY1NTQmIyIGFRQWARNkeHlkPk8Z' +
  'BgEFWEcNBBhQMVVFQllHR0cKi4qKjS4hDTMP1v0ISCIwSV1eEGRrcV9gagAAAgA3//YCAQIiABcAHgAAATIWFhUVIRYWMzI2' +
  'NxUGBiMiJiY1NDY2FyIGByEmJgEkRWM1/pECWVAzTyopUDdMdUE7a0Y/SQcBEQE+AiI8bUk1W18TEk0SET57WVh+REhRSERV' +
  'AAEADwAAAYMC/QAXAAABIxEjESM1NzU0NjMyFhcHJiYjIgYVFTMBTIdYXl5cUiA1ExcQKhYsK4cB1P4sAdQpHh9oWwsHRQUK' +
  'Oz8jAAACADf/EAISAiIAHgArAAABMhYXMzczERQGIyInNRYzMjY1NTQ2NyMGIyImNTQ2FyIGFRQWMzI2NTU0JgETNVUeBQxG' +
  'dXt2S093RU8CAQQ2cGh1dXNDSklGUUpMAiIoKUf933N0IlEqUUYVDC0JUZKDgJdKa2NjaVdhFW5fAAABAFUAAAIZAvgAFQAA' +
  'ExQHMzY2MzIWFREjETQjIgYVESMRM60FBhpZNGJiV3haQ1hYAhkoIykqXWf+owFXgWVe/usC+AAAAgBOAAAAtQLhAAsADwAA' +
  'EzIWFRQGIyImNTQ2FxEjEYIUHx8UFh4eQVgC4RsdHBwcHB0byf3oAhgAAAL/yf8QALUC4QALABsAABM0NjMyFhUUBiMiJgMi' +
  'Jic1FhYzMjY1ETMRFAZOHhYUHx8UFh44GSYODyATICpYSAKpHRsbHRwcHPyDBwVHBAYjMQJr/ZhLVQABAFUAAAINAvgAEwAA' +
  'ExQGBzM+Ajc3MwcTIycHFSMRM6wDAQQGGBkJq2fZ6Gq6PVdXAWsQNBMIHh8KteX+zfo1xQL4AAEAVQAAAK0C+AADAAAzIxEz' +
  'rVhYAvgAAAEAVQAAA1YCIgAhAAABMhYVESMRNCMiBhURIxE0IyIGFREjETMXMzY2MzIXMzY2AqFbWldtTkNXblE+WEcNBRlV' +
  'MH4mBRtdAiJdaP6jAVl/Wlb+2AFZf2Re/uoCGEkqKVouLAABAFUAAAIZAiIAEwAAATIWFREjETQjIgYVESMRMxczNjYBV2Bi' +
  'V3hZRFhHDQUaXAIiXWj+owFXgWRe/uoCGEkqKQACADf/9gInAiIADQAZAAABFAYjIiYmNTQ2MzIWFgUUFjMyNjU0JiMiBgIn' +
  'h3NHb0CGc0lvP/5rS1JRTExSUkoBDYWSQX1ZhZBBe1lfb29fX2xsAAACAFX/EAIwAiIAFQAjAAABMhYVFAYjIiYnIxYWFRUj' +
  'ETMXMzY2FyIGBxUUFjMyNjY1NCYBVGN5eWQ+URcGAgRYSAwEGE4xUkMCQVgxPx9HAiKKi4mOLx8RNBPcAwhJIzBKXF4RY2s2' +
  'XTxcbgACADf/EAISAiIAFQAiAAAFNDY3IwYGIyImNTQ2MzIWFzM3MxEjAzI2NzU0JiMiBhUUFgG6AgMGF1FAYXl7Yj9QGAQN' +
  'RliYU0UBRFdIRkcLEjARIjCLioqNMCNJ/PgBL1teEmZpcV9fawAAAQBVAAABjgIiABMAAAEyFhcHJiYjIgYGFREjETMXMzY2' +
  'AU8PIw0LDR8OKUgrWEgKBBpSAiIDA1EDBC1RNv7iAhhiLEAAAAEAM//2AbICIgApAAAlFAYjIiYnNRYWMzI2NTQmJicuAjU0' +
  'NjMyFhcHJiYjIgYVFBYWFx4CAbJ0YjhRHyBbL0M8Fjk1NEoob1oxVSUeIkonNjkaPTMzSCaUTlASEFAQGyskFCAgFBQoOCxE' +
  'ShMRRg4UIx4WHx0UEyg5AAABABD/9gFTApMAGAAAJTI2NxUGBiMiJiY1ESM1NzczFTMVIxEUFgEIFCoNDjQYKkcsTE0jNJub' +
  'Lz4HBEMHCR1IQQE4KiNye0T+yjEvAAABAE//9gIVAhgAEwAAAREjJyMGBiMiJjURMxEUMzI2NRECFUgNBBpcNGFiWXdZRQIY' +
  '/ehHKiddZgFf/qeAZF4BFwABAAAAAAH8AhgADwAAMwMzEx4CFzM+AjcTMwPLy15yCBIOAwQEDxMHcl7MAhj+xBY2MRERMjYV' +
  'ATz96AABAAsAAQMHAhkAIgAAASYmJyMGBgcDIwMzExYWFzM+AjcTMxMWFhczNjY3EzMDIwGvDRMFBAQSDmBkk1tKCxQEBAQL' +
  'DgdfYFwLFQQEAxUMS1qVZwEvKU8WFk8q/tMCGP7iK1gdETI3FgEu/tIiUB0ZWC4BHv3oAAABABIAAAH/AhgACwAAEwMzFzcz' +
  'AxMjJwcj1LlkioljucNkkpRjARIBBsrK/vr+7tbWAAEAAf8QAf4CGAAaAAATMxMWFhczNjY3EzMDBgYjIiYnNRYWMzI2NzcB' +
  'XnQPGAYEBhoObV/nHFlOGCQNCx8RLjkQHAIY/s8oSSEZUSkBMP2eTFoFA0YCBDQrRwAAAQAnAAABrwIYAAkAACEhNQEhNSEV' +
  'ASEBr/54ASD+8QFw/uQBIzoBmkRC/m4AAAEAHP9iAVwCygAdAAAFJiY1NTQmIzU2NjU1NDYzFQYGFRUUBxUWFRUUFhcBXFxq' +
  'Pzs7P25YNDttbTo1ngFOUJMzK0kBKjKUUE5IASwxkGcTBhNnkzErAQABAO//DwE4AvgAAwAAEzMRI+9JSQL4/BcAAAEAIP9i' +
  'AWACygAdAAAXNjY1NTQ3NSY1NTQmJzUWFhUVFBYzFQYGFRUUBiMgNDttbTo1XGo/Ozs/blhWAisxkWcTBhNnkjErAUgBTlCS' +
  'MytJASoylU9PAAABADIBHwIJAaIAFwAAASYmIyIGBzU2MzIWFxYWMzI2NxUGIyImAQ0kLxYcPhgwSB05LiQvFR0+GDFHHDsB' +
  'PxALIhlONQwUEAsiGU02DQACAEj/SgDEAiIACwAPAAATFAYjIiY1NDYzMhYHMxMjxCQaGSUlGRokXDoZbAHeJR4eJSQgILj+' +
  'AAAAAQBb//YB5QLUACEAAAEWFhcHJiYjIgYVFBYzMjY3FQYGBxUjNS4CNTQ2Njc1MwFhJkUZGhpCG1JNT0wsQR8bOidDO1cw' +
  'MFg6RAKEARELSQoQZWhoXxENTQ0PAmFkCTxyWVt0PglUAAABACAAAAIXAtMAIAAAATIWFwcmJiMiBhUVMxUjFRQGByEVITU2' +
  'NjU1IzUzNTQ2AU43WCIfHkkpOTzMzCoaAYD+CSs4YGBvAtMYEUYOGDtCi0JoPTsQUEoLQEJpQpRZZAACADsAgAH/AkIAIQAx' +
  'AAATNDY3JzcXNjYzMhYXNxcHFhYVFAcXBycGBiMiJwcnNyYmNxQWFjMyNjY1NCYmIyIGBloTEEIxQhc6Hx83GEMwQA8UIz8v' +
  'Qxc4H0AwQjBBEBNDIjskJTojIzolJDsiAWEeORdEL0AREhIRQC9DFzkfPzFCL0AQEiNAL0IXOR8kOiMjOiQlOyMjOwAAAQAO' +
  'AAACLALKABYAAAETMwMzFSMVMxUjFSM1IzUzNSM1MwMzAR2zXMl8l5eXVpeXl3rHXQFtAV3+iUBSQIGBQFJAAXcAAAIA7/8P' +
  'ATgC+AADAAcAABMzESMVMxEj70lJSUkC+P6D7/6DAAIAO//7Ab8C/QAzAEEAABM0NjcmJjU0NjMyFhcHJiYjIgYVFBYXFhYV' +
  'FAYHFhYVFAYjIiYnNRYWMzI2NTQmJicuAjcUFhcXNjY1NCYmJwYGQzAfJChmXzhOJRsiRDA8MThMTVYuHSMnc2c3UiAgXi9K' +
  'OBM3NzRLJ0s/UBYXKRtEPhwsAYsyPQ8UNyg8RRMPQw4THxwcJxwcSDwzQRETNSZFTBEQSw8aKxwTHB8UFCo6NiUzHggOKyIZ' +
  'KCUTBy4AAAIAlQJ3Aa4C2gALABcAABM0NjMyFhUUBiMiJjc0NjMyFhUUBiMiJpUcExMcHBMTHLwbExMcHBMTGwKpGhcXGhkZ' +
  'GRkaFxcaGRkZAAADADH/9gMPAtQAEwAmAD8AAAUiLgI1ND4CMzIeAhUUDgInMj4CNTQuAiMiBgYVFB4CNyImNTQ2NjMyFwcm' +
  'IyIGFRQWMzI2NxUGBgGgUIZjNjZjhlBMhWU5NmOGUEBwVjAuU3FEWo1QLlNyU2NiLlpBQTodMis7QTlCFzkZGDIKNmOGUFCG' +
  'YzY2Y4ZQUIZjNjUuVXJFQXJWMVGNXEFyVjFae2VBZTkePRpUSkxTDQpACg4AAgAgAX8BNALSABkAJAAAEzIWFRUjJwYGIyIm' +
  'NTQ3NzU0JiMiBgcnNjYXBgYVFBYzMjY1NbFBQi8MFDgmLzieOCodHDIXFhpBNzwqHRkzLQLSNjvcKhUbMTJjBgIWIRoPCzEN' +
  'ELQCHxsZFy8oFwACACgAOAHWAdcABgANAAATNxcHFwcnNzcXBxcHJyioP4yMP6jGqj6MjD6qAQ7JJKurJckNySSrqyXJAAAB' +
  'ADIAgAIIAYQABQAAAREjNSE1AghH/nEBhP78vUcA//8AKADlARoBMwIGAA4AAAAEADH/9gMPAtQAEwAmADQAPQAABSIuAjU0' +
  'PgIzMh4CFRQOAicyPgI1NC4CIyIGBhUUHgInETMyFhUUBgcXIycjFTcyNjU0JiMjFQGgUIZjNjZjhlBMhWU5NmOGUEBwVjAu' +
  'U3FEWo1QLlNyRYBSTDAedFZkPjInLCgsMQo2Y4ZQUIZjNjZjhlBQhmM2NS5VckVBclYxUY1cQXJWMV8BtUBBLzcMwq2t6ygf' +
  'IyCKAAAB//0C+AH3AzoAAwAAASE1IQH3/gYB+gL4QgAAAgA3AaEBdQLUAAsAFwAAEyImNTQ2MzIWFRQGJzI2NTQmIyIGFRQW' +
  '1khXVklHWFhGMC0vLjEuLgGhVUREVlZERFU7NCosNDQsKjQAAAIAMgAAAgkCVgALAA8AAAEzFSMVIzUjNTM1MwE1IRUBQcfH' +
  'SMfHSP7xAdcBh0fOzkfP/apHRwAAAQAYAaABMwNVABkAAAEhNTc+AjU0JiMiBgcnNjYzMhYVFAYHBzMBMv7mcykpDyUeHjEa' +
  'Ix1FK0BJOzhRwwGgNnAnMScWICAXFC4ZHj83MU41TQAAAQARAZgBQQNVACgAABMyFhUUBgcVFhYVFAYjIiYnNRYzMjY1NCYj' +
  'IzUzMjY1NCYjIgYHJzY2pUdIKx4nL1RZJUAeRj40MDo0OTkyLykdHzUbJB9FA1U+MCg0CgMHMyk6SQ0PPyIpIyQhNycfIB0V' +
  'ES4XGgABACgCXgDxAv4ACwAAEw4CByM1PgI3M/EMMjkYOg8jIgtqAvQSOTkSDBM0NxYAAQBV/xACGgIYABkAAAERIycjBgYj' +
  'IiYnIxYWFRUjETMRFDMyNjURAhpHDgUZUDgnOBQEAgNYWHhZRAIY/ehIKCoZFBI8KZwDCP6mf2ReARcAAAEAN/+BAiUC+AAS' +
  'AAAFIxEjESMRBgYjIiYmNTQ2NjMhAiU6ZjoPJxE+XDM3ZEEBEn8DP/zBAZAEBS5sW2BtLv//AEgBHQDEAaQCBwAPAAABKwAB' +
  'AA7/EADUAAAAFAAAFxQGIyInNRYWMzI2NTQmJzczBxYW1EpKIBIJHg4kJjUmKzoaJDOLMDUFNwIDExkaGAVWNQgoAAEAJQGg' +
  'APADTAAMAAATESMRNDY3BgYHByc38EcDAQoYDTYjggNM/lQBFBoqFQkVCScxXAACACABfwFZAtIACwAXAAABFAYjIiY1NDYz' +
  'MhYHFBYzMjY1NCYjIgYBWVZIQ1hUSUdV+iwxMSwsMTEsAilRWVdTUldWUzo7Ozo7OTkAAgAnADgB1QHXAAYADQAAAQcnNyc3' +
  'FwcHJzcnNxcB1ao+jIw+qsepPoyMPqkBAcklq6skyQ3JJaurJMkABAAiAAAC4ALKAAMAEAAbACQAADMBMwEDNDY3BgYHByc3' +
  'MxEjATUjNRMzETMVIxUnMzU0NjcGBgd+AbRL/kwjAwEKGA02I4JJRwGyw8VJPT3IfQIBBSALAsr9NgIyGioVCRUJJzFc/lT+' +
  '4mA0ARv+7TxgnF0VOBgLMREAAAMAFgAAAtgCygADABAAKgAAMwEzAQM0NjcGBgcHJzczESMBNTc+AjU0JiMiBgcnNjYzMhYV' +
  'FAYHBzMVYAG0S/5MEQMBChgNNiOCSUcBI3MpKQ8lHh4xGiMdRStASTs4UcMCyv02AjIaKhUJFQknMVz+VP7iNnAnMScWICAX' +
  'FC4ZHj83MU41TT4AAAQADwAAAwQC0wAoACwANwBAAAATIiYnNRYzMjY1NCYjIzUzMjY1NCYjIgYHJzY2MzIWFRQGBxUWFhUU' +
  'BgMBMwEhNSM1EzMRMxUjFSczNTQ2NwYGB5IlQB5GPjQwOjQ5OTIvKR0fNRskH0UuR0grHicvVEEBtEv+TAGHw8VJPT3IfQIB' +
  'BSALARYNDz8iKSMkITcnHyAdFREuFxo+MCg0CgMHMyk6Sf7qAsr9NmA0ARv+7TxgnF0VOBgLMREAAgAY/0ABpAIiAAsAKwAA' +
  'ARQGIyImNTQ2MzIWBxQGBgcOAhUUFjMyNjcXBgYjIiY1NDY2Nz4CNTUzATsjGxkkJBkbIxcPJCEmLBI/OjJMIh8oYTxfaB01' +
  'JCIiDEYB3iUeHiUkICDSJTgxHCAtKh4wNBoQRhUcXlEtPzUeHSkqHBEA//8AAAAAAn4DsAImACIAAAAHAEEAlACy//8AAAAA' +
  'An4DsAImACIAAAAHAHQA4QCy//8AAAAAAn4DsAImACIAAAAHAMAAbQCy//8AAAAAAn4DkQImACIAAAAHAMIAXwCy//8AAAAA' +
  'An4DjAImACIAAAAHAGgAHQCy//8AAAAAAn4DbgImACIAAAAHAMEAqAA9AAL//wAAAzUCygAPABMAACEhNSMHIwEhFSEVIRUh' +
  'FSElMxEjAzX+jPprXQFTAeP+5gEH/vkBGv211zrd3QLKT99O/94BTf//AD3/EAJZAtQCJgAkAAAABwB4AQUAAP//AGEAAAHw' +
  'A7ACJgAmAAAABwBBAIcAsv//AGEAAAHwA7ACJgAmAAAABwB0ANQAsv//AGEAAAHwA7ACJgAmAAAABwDAAGAAsv//AGEAAAHw' +
  'A4wCJgAmAAAABwBoABAAsv//ACgAAAEqA7ACJgAqAAAABwBBAAAAsv//ACgAAAE+A7ACJgAqAAAABwB0AE0Asv//AAEAAAFT' +
  'A7ACJgAqAAAABwDA/9kAsv//AB4AAAE3A4wCJgAqAAAABwBo/4kAsgACAB4AAAKdAsoADQAZAAABMhYWFRQGIyMRIzUzERcj' +
  'FTMVIxUzIBE0JgE9a55XxbG/SkrIbrKyWgEijgLKUJtztbcBOk4BQk31Tu0BHI+F//8AYQAAApcDkQImAC8AAAAHAMIAnQCy' +
  '//8APf/2AtADsAImADAAAAAHAEEA3QCy//8APf/2AtADsAImADAAAAAHAHQBKgCy//8APf/2AtADsAImADAAAAAHAMAAtgCy' +
  '//8APf/2AtADkQImADAAAAAHAMIAqACy//8APf/2AtADjAImADAAAAAHAGgAZgCyAAEAQACEAfoCPgALAAABFwcXBycHJzcn' +
  'NxcByDKqqTKrpzSpqjSpAj4zqqozqakzqqk0qwADAD3/4QLQAuoAFwAgACkAAAEUBgYjIicHJzcmJjU0NjYzMhYXNxcHFgUU' +
  'FhcBJiMiBgU0JwEWFjMyNgLQS5JscEkwPTQsLEiTcDRZJS49M179zBcYAT80TnlzAdUz/sAaRSp6cAFmb6VcL0QoSjGMV26k' +
  'XBgVQilHY7E9ZCUBwyOZh4FJ/joSFJsA//8AWv/2AoADsAImADYAAAAHAEEAxACy//8AWv/2AoADsAImADYAAAAHAHQBEQCy' +
  '//8AWv/2AoADsAImADYAAAAHAMAAnQCy//8AWv/2AoADjAImADYAAAAHAGgATQCy//8AAAAAAjYDsAImADoAAAAHAHQAvgCy' +
  'AAIAYQAAAioCygANABYAAAEUBgYjIxUjETMVMzIWBTI2NTQmIyMRAio0fW1RWlpgkX7+2WlhV2JZAX48Z0CbAsp8bvlDT0VD' +
  '/uYAAQBV//YCSgL9ADYAAAEUDgMVFBYWFxYWFRQGIyImJzUWFjMyNjU0JicmJjU0PgM1NCYjIgYGFREjETQ2NjMyFgIKHCoq' +
  'HA0mJTY+Z1MvSBoaTCg3MCk1Py4bKSkbRzgjPSVYOmQ/YXcCaSIzJyAfEg0WHRkkSztVThIQTxAaLigkMiIpOygfLCEgJhsq' +
  'JhMuK/24AkhDTyNK//8ALv/2AeAC/gImAEIAAAAGAEFvAP//AC7/9gHgAv4CJgBCAAAABwB0ALwAAP//AC7/9gHgAv4CJgBC' +
  'AAAABgDASAD//wAu//YB4ALfAiYAQgAAAAYAwjoA//8ALv/2AeAC2gImAEIAAAAGAGj4AP//AC7/9gHgAzECJgBCAAAABwDB' +
  'AIMAAAADAC7/9gMtAiIALAAzAD4AAAEyFhYVFSEWFjMyNjcVBgYjIicGBiMiJjU0Njc3NTQmIyIGByc2NjMyFhc2NhciBgcz' +
  'NCYFBgYVFBYzMjY1NQJbQV4z/qkCT0oyTCYoTTKNPiJcTUlheHxaPTMoTSEbI2QxPlEVGlQ1OkMF+Dn+mF5IMyo/VQIiPGxI' +
  'NmBbExJNEhFxND1NUlBXBAMiQTQYEUIUGiktKS5IT0pFVNcEODMtKktOMAD//wA3/xABvwIiAiYARAAAAAcAeACqAAD//wA3' +
  '//YCAQL+AiYARgAAAAYAQXMA//8AN//2AgEC/gImAEYAAAAHAHQAwAAA//8AN//2AgEC/gImAEYAAAAGAMBMAP//ADf/9gIB' +
  'AtoCJgBGAAAABgBo/AD/////AAAAyAL+AiYAywAAAAYAQdcA//8ATAAAARUC/gImAMsAAAAGAHQkAP///9gAAAEqAv4CJgDL' +
  'AAAABgDAsAD////1AAABDgLaAiYAywAAAAcAaP9gAAAAAgA3//YCJwL9ACAALAAAExYWFzcXBxYWFRQGIyImJjU0NjMyFhc3' +
  'JiYnByc3JiYnEyIGFRQWMzI2NTQm2CBBHXMmY0RXhnRIbz9/bDVPGAQQQiqCJnAVLhd7VEtMU1NMTgL9DyQVQzY5QLx6jo87' +
  'bUtwgBweAjlgJks3QA4bDP7RWVNJX2FcPln//wBVAAACGQLfAiYATwAAAAYAwlYA//8AN//2AicC/gImAFAAAAAHAEEAhQAA' +
  '//8AN//2AicC/gImAFAAAAAHAHQA0gAA//8AN//2AicC/gImAFAAAAAGAMBeAP//ADf/9gInAt8CJgBQAAAABgDCUAD//wA3' +
  '//YCJwLaAiYAUAAAAAYAaA4AAAMAMgB5AgkCRwALAA8AGwAAASImNTQ2MzIWFRQGBTUhFQciJjU0NjMyFhUUBgEdFyEhFxcg' +
  'IP7+AdfsFyEhFxcgIAHOHSAiGhoiIB2RR0fEHSAiGhoiIB0AAAMAN//fAicCNgAVAB4AJgAAARQGIyInByc3JiY1NDYzMhc3' +
  'FwcWFgUUFhcTJiMiBgU0JwMWMzI2AieHc0k4KDotHyGGc0k6JzstHSL+awsN3CQ0UkoBOhfcIjRRTAENhZIhOCc+JGVAhZAk' +
  'OCY/I2M+JkEZATIZbF9KMf7OF2///wBP//YCFQL+AiYAVgAAAAcAQQCLAAD//wBP//YCFQL+AiYAVgAAAAcAdADYAAD//wBP' +
  '//YCFQL+AiYAVgAAAAYAwGQA//8AT//2AhUC2gImAFYAAAAGAGgUAP//AAH/EAH+Av4CJgBaAAAABwB0AKIAAAACAFX/EAIw' +
  'AvgAGQAmAAABFAYjIiYnIx4CFRUjETMVFAYHMzY2MzIWBzQmIyIGBxUUFjMyNgIweWM/UBgGAQMCWFgCAQQYTkBjeVtGSlJE' +
  'AkFYSkUBDYmOLiAHICIL4APo4A4tDSIwjIhlZVxcE2Nra///AAH/EAH+AtoCJgBaAAAABgBo3gAAAQAoAl4BegL+ABIAABMe' +
  'AhcVIyYmJwYGByM1PgI3/QwtMRM+GjgbGzYaPBMvLA0C/hY3NRMLEC8bGy4RCxQ0NxYAAgAoAl4BBAMxAAsAFwAAEyImNTQ2' +
  'MzIWFRQGJzI2NTQmIyIGFRQWlTE8PDEvQD8wGR8gGBggHQJeODIyNzcxMzgyHhoaHh4aGh4AAAEAKAJeAZcC3wAVAAATNjYz' +
  'MhYWMzI2NzMGBiMiJiYjIgYHKAY5Lx41MBUXGQcyBjgvHDUxFhgYBwJeO0UdHB0dOkYcHR0dAAEAKADlAcwBMwADAAA3NSEV' +
  'KAGk5U5OAAEAKADlA8ABMwADAAA3NSEVKAOY5U5OAAEADAHVAKMCygAJAAATNjY3Mw4CByMMDjAYQQkUEAVfAeA1gDUmV1Uj' +
  'AAEADAHVAKMCygAJAAATBgYHIz4CNzOjDTEYQQoTEAVeAr80gTUmV1Uj//8AH/9/ALYAdAAHAMYAE/2qAAEADAHVAKQCygAJ' +
  'AAATHgIXIyYmJzdyBRAUCUEZMA4HAsojVVcmNYE0CwAAAgAMAdUBWwLKAAgAEQAAAQYGByMnNjY3IwYGByMnNjY3AVsOHAhf' +
  'Bw4wGXgOHAheBg4vGQLKOoc0CzV/NjqHNAs1fzYAAAIADAHVAVsCygAJABMAAAEGBgcjPgI3MwcGBgcjPgI3MwFbDTEYQgoT' +
  'EQVesg0xGEAKEhAFXgK/NYA1JldVIws1gDUmV1UjAAEAVQAAAK0CGAADAAAzIxEzrVhYAhgAAAEAMgE9AggBhAADAAABFSE1' +
  'Agj+KgGER0cAAQAAAM0BBAAYAGYABgABAAAAAAAAAAAAAAAAAAQAAQAAABQAFAAxAEcAdwDCAQsBXQFrAYUBoAG/AdQB6AH0' +
  'AgoCGgJEAl0CiQLHAuwDHQNeA3ADwQQDBCkETgRhBHQEhwTHBTMFVwWMBbcF1wXuBgIGNAZLBmMGgAadBqwG0gbzByAHQwd2' +
  'B58H3QfuCA0IKghkCH8IlQisCL0IzAjdCPAI/QkUCU8JggmsCeAKEgo4CncKmgq3CuMLBQsRC0MLZAuOC8QL+QwcDFoMgQyi' +
  'DMAM/A0VDUMNWg2GDZMNvw3mDeYOAw43DmcOtA7XDukPSQ9vD8gP/xAdEC0QNRCMEJoQwBDcEQYRQBFXEYARoBGpEcsR5RIL' +
  'EikSZxKsEwoTSxNXE2MTbxN7E4cTkxO2E8ITzhPaE+YT8hP+FAoUFhQiFEoUVhRiFG4UehSGFJIUrBTyFP4VChUWFSIVLhVT' +
  'FaAVqxW3FcIVzRXYFeQWQBZMFlcWYxZuFnkWhBaPFpoWphbrFvYXAhcOFxkXJBcvF1wXnBeoF7QXvxfKF9YYDxgaGDsYYRiF' +
  'GJEYnRiyGMcY0BjmGQkZLRk5GUYAAQAAAAID1+5NJU9fDzz1AAcD6AAAAADdgNPnAAAAAONjwLf9k/57CvAEKwAAAAYAAgAA' +
  'AAAAAAJYAF4BBAAAAQ0ASAGYAEEChgAZAjwAPgM/ADEC3AA1AOEAQQEsACgBLAAeAicAKQI8ADIBDAApAUIAKAEMAEgBdAAK' +
  'AjwAMQI8AFkCPAAwAjwALQI8ABUCPAA/AjwANwI8ACwCPAAxAjwAMgEMAEgBDAAfAjwAMgI8ADgCPAAyAbIADAODADoCfwAA' +
  'AooAYQJ4AD0C2gBhAiwAYQIHAGEC2AA9AuUAYQFTACgBEf+yAmsAYQIMAGEDiwBhAvgAYQMNAD0CXQBhAw0APQJuAGECJQAz' +
  'AiwACgLbAFoCWAAAA6IADAJKAAQCNgAAAjwAJgFJAFABdAAKAUkAGQI8ACYBvP/+ARkAKAIxAC4CZwBVAeAANwJnADcCNAA3' +
  'AVgADwJnADcCagBVAQIATgEC/8kCFgBVAQIAVQOnAFUCagBVAl0ANwJnAFUCZwA3AZ0AVQHfADMBaQAQAmoATwH8AAADEgAL' +
  'AhEAEgH+AAEB1gAnAXwAHAInAO8BfAAgAjwAMgEEAAABDQBIAjwAWwI8ACACPAA7AjwADgInAO8CAQA7AkQAlQNAADEBZQAg' +
  'Af0AKAI8ADIBQgAoA0AAMQH0//0BrAA3AjwAMgFeABgBXgARARkAKAJvAFUCjwA3AQwASADhAA4BXgAlAXgAIAH9ACcC6QAi' +
  'AwMAFgMNAA8BsgAYAn8AAAJ/AAACfwAAAn8AAAJ/AAACfwAAA3H//wJ4AD0CLABhAiwAYQIsAGECLABhAVMAKAFTACgBUwAB' +
  'AVMAHgLaAB4C+ABhAw0APQMNAD0DDQA9Aw0APQMNAD0CPABAAw0APQLbAFoC2wBaAtsAWgLbAFoCNgAAAl0AYQJ3AFUCMQAu' +
  'AjEALgIxAC4CMQAuAjEALgIxAC4DYAAuAeAANwI0ADcCNAA3AjQANwI0ADcBAv//AQIATAEC/9gBAv/1Al0ANwJqAFUCXQA3' +
  'Al0ANwJdADcCXQA3Al0ANwI8ADICXQA3AmoATwJqAE8CagBPAmoATwH+AAECZwBVAf4AAQGiACgBLAAoAb8AKAH0ACgD6AAo' +
  'AK8ADACvAAwA+gAfAK8ADAFnAAwBZwAMAQIAVQI8ADIAAQAABC3+2wAACxj9k/2UCvAD6AAAAAAAAAAAAAAAAAAAAM0ABAJB' +
  'AZAABQAAAooCWAAAAEsCigJYAAABXgAyAUIAAAILBQIEBQQCAgSAAAADAAAAAAAAAAAAAAAAR09PRwDAACAiEgQt/tsAAARk' +
  'AYsAAAABAAAAAAIYAsoAAAAgAAQAAAACAAAAAwAAABQAAwABAAAAFAAEAEAAAAAMAAgAAgAEAH4A/yAUIB0iEv//AAAAIACg' +
  'IBMgGCIS////4f/A4LDgrd66AAEAAAAAAAAAAAAAAAAAAAAHAFoAAwABBAkAAAC2AAAAAwABBAkAAQASALYAAwABBAkAAgAO' +
  'AMgAAwABBAkAAwA2ANYAAwABBAkABAAiAQwAAwABBAkABQBUAS4AAwABBAkABgAgAYIAQwBvAHAAeQByAGkAZwBoAHQAIAAy' +
  'ADAAMgAyACAAVABoAGUAIABOAG8AdABvACAAUAByAG8AagBlAGMAdAAgAEEAdQB0AGgAbwByAHMAIAAoAGgAdAB0AHAAcwA6' +
  'AC8ALwBnAGkAdABoAHUAYgAuAGMAbwBtAC8AbgBvAHQAbwBmAG8AbgB0AHMALwBsAGEAdABpAG4ALQBnAHIAZQBlAGsALQBj' +
  'AHkAcgBpAGwAbABpAGMAKQBOAG8AdABvACAAUwBhAG4AcwBSAGUAZwB1AGwAYQByADIALgAwADEANQA7AEcATwBPAEcAOwBO' +
  'AG8AdABvAFMAYQBuAHMALQBSAGUAZwB1AGwAYQByAE4AbwB0AG8AIABTAGEAbgBzACAAUgBlAGcAdQBsAGEAcgBWAGUAcgBz' +
  'AGkAbwBuACAAMgAuADAAMQA1ADsAIAB0AHQAZgBhAHUAdABvAGgAaQBuAHQAIAAoAHYAMQAuADgALgA0AC4ANwAtADUAZAA1' +
  'AGIAKQBOAG8AdABvAFMAYQBuAHMALQBSAGUAZwB1AGwAYQByAAMAAAAAAAD/nAAyAAAAAAAAAAAAAAAAAAAAAAAAAAA=';

/** The typeface's bytes, decoded once and held, since every label read after the
 * first reads the same font. */
let decoded: Uint8Array | undefined;

/** The shipped typeface's bytes. */
export function fontBytes(): Uint8Array {
  if (decoded) return decoded;
  const binary = atob(ENCODED);
  const bytes = new Uint8Array(binary.length);
  for (let at = 0; at < binary.length; at += 1) bytes[at] = binary.charCodeAt(at);
  decoded = bytes;
  return decoded;
}
