/**
 * The shipped typeface as the bytes a font reader parses, written by
 * `font/build.mjs` and not by hand.
 *
 * A font arrives as a module rather than as a file beside the code because a file
 * is reached by a path, and a path is a different thing in Node, behind a bundler
 * and in a browser with neither. An import is the same thing everywhere. The
 * module is loaded by the call that needs it, so a consumer who never draws a
 * label never fetches these bytes.
 *
 * Noto Sans, subset to Latin-1 and the punctuation a figure writes, under the SIL
 * Open Font License 1.1. The licence text ships beside the generator.
 */

/** The subset as base64, which is what a module can carry and a byte array
 * cannot. */
const ENCODED =
  'AAEAAAAKAIAAAwAgT1MvMmlSAAwAADhcAAAAYGNtYXAiwURFAAA4vAAAAFRnbHlmSiOQJgAAAKwAADJkaGVhZCiD2/4AADTM' +
  'AAAANmhoZWEMsww8AAA4OAAAACRobXR4ru8n0QAANQQAAAM0bG9jYZwTqZ0AADMwAAABnG1heHAA8AFsAAAzEAAAACBuYW1l' +
  'Km9DIQAAORAAAAH8cG9zdP+fADIAADsMAAAAIAACAEj/8gDEAsoAAwAPAAA3IwMzAzQ2MzIWFRQGIyImozkZa3QkGhklJRka' +
  'JMkCAf1sJR4eJSQgIAAAAgBBAcgBVwLKAAMABwAAEwMjAyEDIwOgFDcUARYUNxQCyv7+AQL+/gECAAACABkAAAJsAsoAGwAf' +
  'AAABBzMVIwcjNyMHIzcjNTM3IzUzNzMHMzczBzMVBTM3IwHgH4mWKUcpjydGJn6LIIaSKEgokChFKH/+f48fjwG0oEPR0dHR' +
  'Q6BC1NTU1EKgoAADAD7/xgIEAvcAIgApADAAADcmJic1FhYXNSYmNTQ2NzUzFRYWFwcmJicVHgIVFAYHFSMRBgYVFBYXEzY2' +
  'NTQmJ/03aCAiajNjXGdYQDVXJBsgTShCWC1oX0A2My08QDs2MEExAREPVRAYAcobUkdKVAVYVwEVD0oNEwPJEys/MkZXCm8C' +
  'jAQqISgrD/7iBisiJicQAAAFADH/9gMOAtQACwAPABkAJQAvAAATMhYVFAYjIiY1NDYFASMBBSIGFRQWMzI1NAUyFhUUBiMi' +
  'JjU0NhciBhUUFjMyNTTDSkxJTUdLRgIV/nRNAYz+hCYjIyZNAWhJTUlNR0tGTCYjIyZNAtR1amp3d2pqdQr9NgLKNFFQUFKi' +
  'oeB1amp3d2pqdT9QUFFRoqAAAAMANf/2AtoC1QAfACsANQAAATIWFRQGBxc2NjczBgYHFyMnBgYjIiY1NDY3JiY1NDYXIgYV' +
  'FBYXNjY1NCYDBgYVFBYzMjY3ATBQXVE+wRohC1kQMCaSd1cvdFNnelNHIDdjUio1JiQ7MzBSNj1KPkBcHwLVUUk/WCS6H1Ev' +
  'QG4pjlQqNGZeTV0oJFI3SlJILCckPSUiPSgkLv7IIEI2N0IqHQAAAQBBAcgAoALKAAMAABMDIwOgFDcUAsr+/gECAAEAKP9i' +
  'AQ4CygANAAATNDY3MwYGFRQWFyMmJihHTFNGR0dFUkxHARJ641te4nd0315Y3wABAB7/YgEEAsoADQAAARQGByM2NjU0Jicz' +
  'FhYBBEdMUkVHR0ZTTEcBEnnfWF7fdHfiXlvjAAABACkBNgH8AvgADgAAAQc3FwcXBycHJzcnNxcnAUIUwA64d1ZVTVl1tg6+' +
  'FQL4wDZcD54vr68vng9cNsAAAAEAMgBvAggCUwALAAABMxUjFSM1IzUzNTMBQcfHSMfHSAGER87OR88AAAEAKf9/AMAAdAAI' +
  'AAA3BgYHIzY2NzPADTEYQQ4dB15pNX82OYg0AAABACgA5QEaATMAAwAANzUzFSjy5U5OAAABAEj/8gDEAHkACwAANzQ2MzIW' +
  'FRQGIyImSCQZGiUlGhkkNiUeHiUkICAAAAEACgAAAWoCygADAAABASMBAWr+9lYBCgLK/TYCygAAAgAx//YCCwLVAA0AGQAA' +
  'ARQGBiMiJjU0NjYzMhYFFBYzMjY1NCYjIgYCCzBoVnlzL2hVeHb+fkNRUEVFUFFDAWZzpVjDrXSkV8Guk5KRlJKSkgAAAQBZ' +
  'AAABYwLKAAwAACEjETQ2NwYGBwcnNzMBY1YCAhAaFEwuwUkB8ys0HBAWET47lgABADAAAAIIAtQAGwAAISE1Nz4CNTQmIyIG' +
  'Byc2NjMyFhUUBgYHBxUhAgj+KLs2SiZGODRPKS8qbURkdC5SN5UBaUm9NlRRMDs9JCA7IzFlWThiXzaTBAAAAQAt//YCAwLU' +
  'ACoAAAEUBgcVFhYVFAYGIyImJzUWFjMyNjU0JiMjNTMyNjU0JiMiBgcnNjYzMhYB7VBEVlQ6eV84YCwtaDBgVWlfRUZYW0Y8' +
  'OlIoLCZxSHBtAiNIVQ4EClhHPmE2ERZSFhlLQkM7S0o9NDkiGjweLGQAAAIAFQAAAigCzgAKABQAACUjFSM1ITUBMxEzJzQ2' +
  'NyMGBgcDIQIoaFX+qgFQW2i9BAEECBgL1gEAoqKiSwHh/iPhNEkhEywP/s8AAQA///YCAwLKAB4AAAEyFhUUBiMiJic1FhYz' +
  'MjY1NCYjIgYHJxMhFSEHNjYBE26CjX43YSEkZy9PYVZdHEgWLBsBZv7lERE6AbZuZG9/FBNTFhlLT0ZLCgUcAVFQzwMIAAAC' +
  'ADf/9gINAtQAHgAsAAATND4CMzIWFxUmJiMiDgIHMzY2MzIWFRQGIyImJhcyNjU0JiMiBgYVFBYWNxtHgGUVMxASLRdFXDUY' +
  'AwYXUkBdcntoRG5B8j9ORUUvRiciRAExTZV5SAQFSwYGLlBoOyMxcWhwgESMhlFVRFAnPCArVTcAAQAsAAACCwLKAAYAADMB' +
  'ITUhFQGIASX+fwHf/t4CelBE/XoAAwAx//YCCgLUABsAKAA1AAABMhYVFAYGBx4CFRQGIyImNTQ2NjcmJjU0NjYXIgYVFBYW' +
  'FzY2NTQmAxQWMzI2NTQmJycGBgEdXnglPiUsSCt/a3N8KUQnNEk4YDw3RyM8JDRHRs9KTUlNUkQQQkUC1FhTK0AxExU1RjFa' +
  'aWVbMUg0Eh5VQjdLKEc1MiUyIxAWPjYyNf4oNEVFNzRFGgYcSQAAAgAy//YCCALUAB4ALAAAARQOAiMiJic1FjMyPgI3IwYG' +
  'IyImNTQ2NjMyFhYnIgYVFBYzMjY2NTQmJgIIG0eBZRQ1EScxRls2GAIGFlNBXHE5ZkVEbkDyPk9DRjBGJyJEAZlNlXlIBQVL' +
  'DS5PaToiMXFnS2w6RYuGUlRFTyc8ICtUOAAAAgBI//IAxAImAAsAFwAAEzQ2MzIWFRQGIyImETQ2MzIWFRQGIyImSCQZGiUl' +
  'GhkkJBkaJSUaGSQB4iYeHiYkICD+eCUeHiUkICAAAAIAH/9/AMICJgALABUAABM0NjMyFhUUBiMiJhMGBgcjPgI3M0YkGRol' +
  'JRoZJHENMRhCChMRBV4B4iYeHiYkICD+qzSBNSZXVSMAAQAyAHQCCQJgAAYAACUlNSUVBQUCCf4pAdf+hwF5dM8y606yngAC' +
  'ADgA2QICAecAAwAHAAATNSEVBTUhFTgByv42AcoBoEdHx0dHAAEAMgB0AgkCYAAGAAA3JSU1BRUFMgF5/ocB1/4pwp2zTusy' +
  'zwAAAgAM//IBmALUAB8AKwAANzQ2Njc+AjU0JiMiBgcnNjYzMhYVFAYGBw4CFRUjBzQ2MzIWFRQGIyImjA8lICcrEj47MUwj' +
  'HyhhPF9oHTUkISMMRhcjGxkkJBkbI+QmNzIbISwqHjA0GRFGFRxeUS0/NR4cKikdEZMlHh4lJCAgAAACADr/pwNJAsoAPwBN' +
  'AAABFA4CIyImJyMGBiMiJjU0NjYzMhYXBwYUFRQWMzI2NjU0JiYjIgYGFRQWMzI2NxUGBiMiJiY1ND4CMzIWFgUUFjMyNjc3' +
  'JiYjIgYGA0kVLEAsLjUGBRJGNUxTNF9BLFUYCgElGR8rF0uDU3KdUZyTPW8rK2tBdqhZOm6dY2iiXf4HMys4MQQGDSgVMTwa' +
  'AWUuWEcrNSIlMmZUQmU6DwnLEg8DNCIzVTNdgURepWqUnhsQRBIXWKV0XZ91QVagr0A6VEN9BAYwSwACAAAAAAJ+As0ABwAR' +
  'AAAhJyEHIwEzAQEuAicGBgcHMwIhVv7lVVsBF1EBFv7iAw4NBAcSBlHi3d0Czf0zAgUIKi0MHzsR2AADAGEAAAJUAsoAEAAZ' +
  'ACIAAAEyFhUUBgcVHgIVFAYjIxETMjY1NCYjIxUVETMyNjU0JiMBLYaJRkItSSqFc/veXERTW3aQX0pNYwLKT2I/UwwFByZG' +
  'OGFqAsr+0Ds6OzPjS/79Sjw4RQAAAQA9//YCWQLUABoAAAEiBhUUFjMyNjcVBgYjIiYmNTQ2NjMyFwcmJgGTc4R7ey9UKChV' +
  'O22SSU+abnFUJCFRAoWahoWbEAxODw5apnBspV0qTA8YAAACAGEAAAKdAsoACQARAAABFAYjIxEzMhYWBzQmIyMRMyACncWw' +
  'x9xsnlZfjYF1YQEiAWy1twLKUJt2j4X90AAAAQBhAAAB8ALKAAsAACEhESEVIRUhFSEVIQHw/nEBj/7LASP+3QE1AspP307/' +
  'AAEAYQAAAfACygAJAAAzIxEhFSEVIRUhu1oBj/7LASL+3gLKT/1PAAABAD3/9gKOAtQAIAAAATMRBgYjIiYmNTQ2NjMyFhcH' +
  'JiYjIgYVFBYWMzI2NzUjAZf3OnZLb5hPWKV1PGsuIiZfM4CPN3ZgL0IbnQF5/qITElmlcXCkWxYUThEYmoZVg0kKB9QAAQBh' +
  'AAACgwLKAAsAACEjESERIxEzESERMwKDWv6SWloBbloBTf6zAsr+0gEuAAEAKAAAASoCygALAAAhITU3ESc1IRUHERcBKv7+' +
  'VFQBAlRUNBMCOxQ0NBT9xRMAAAH/sv9CALYCygAQAAAHIiYnNRYWMzI2NjURMxEUBgQYJA4QJBQZLRxaZr4HBkwEBhQyLQLG' +
  '/UFnYgABAGEAAAJrAsoADgAAISMDBxEjETMRNjY3NzMBAmtq/UlaWh4+H8Fp/uUBVUD+6wLK/qAiRCLY/skAAQBhAAAB8wLK' +
  'AAUAADMRMxEhFWFaATgCyv2GUAAAAQBhAAADKgLKABUAACEDIxYWFREjETMTMxMzESMRNDY3IwMBnOsEAwRThdwE4IRZBQIE' +
  '7gJyH2k5/k8Cyv23Akn9NgG3NGYg/Y8AAAEAYQAAApcCygASAAAhIwEjFhYVESMRMwEzLgI1ETMCl2n+ggQCBlNoAX0EAQMD' +
  'VAJRI2g3/nECyv2xEEBMIAGTAAIAPf/2AtAC1QAPABsAAAEUBgYjIiYmNTQ2NjMyFhYFFBYzMjY1NCYjIgYC0EuSbG+TSEiT' +
  'cGuSS/3Mcnl6cHB5eXMBZm+lXFymb26kXFulb4ebm4eHmZkAAAIAYQAAAioCygALABQAAAEyFhUUBgYjIxEjERcjETMyNjU0' +
  'JgEejIA1fWtSWrVbSGZkWALKbmQ7Z0D+6gLKTf7mQk9FRAACAD3/VgLQAtUAFAAgAAABFAYHFyMnIgYjIiYmNTQ2NjMyFhYF' +
  'FBYzMjY1NCYjIgYC0Glnq4GKBg0Gb5NISJNwa5JL/cxyeXpwcHl5cwFmg7gjsqEBXKZvbqRcW6Vvh5ubh4eZmQACAGEAAAJf' +
  'AsoADgAXAAABMhYVFAYGBxMjAyMRIxEXIxEzMjY1NCYBJoV/KkEkxGmtjlrAZmtXUFQCymVmOUwtDf7AASf+2QLKTv73RUNG' +
  'OwAAAQAz//YB9gLUACkAACUUBiMiJic1FhYzMjY1NCYmJyYmNTQ2NjMyFhcHJiYjIgYVFBYWFx4CAfaKdTxmIiRrOVBRHklB' +
  'W106Z0M7YigcJVcvQ0QeRDo/Vy2/X2oSEFYQGj41IzApFyFgUzlRLBYSTRAWOS8kMCYWFzVKAAEACgAAAiECygAHAAAhIxEj' +
  'NSEVIwFDWt8CF94Ce09PAAABAFr/9gKAAsoAEgAAJRQGBiMiJjURMxEUFjMyNjURMwKAPHtfhYtaXV5hV1n8SndFkXcBzP4x' +
  'V2BnUQHOAAEAAAAAAlgCygAMAAABAyMDMxMWFhc2NjcTAlj/Wv9eoRAWBwcWEKACyv02Asr+NixNIyNOLQHIAAABAAwAAAOV' +
  'AsoAHwAAAQMjAy4CJwYGBwMjAzMTFhYXNjY3EzMTFhYXNjY3EwOVvluLCBAKAgETDodbvV5vDBEFBRQNfl2DDhQFBRIMbgLK' +
  '/TYB1B06LQkNVS7+LwLK/kwuViYnXCwBr/5OLlsjJVcvAbMAAAEABAAAAkYCygALAAAhIwMDIxMDMxMTMwMCRma9wF/t3mSv' +
  'sF/dATb+ygF0AVb+6AEY/qwAAAEAAAAAAjYCygAIAAABEzMDESMRAzMBG7ph7lruYgFrAV/+S/7rAREBuQAAAQAmAAACFQLK' +
  'AAkAACEhNQEhNSEVASECFf4RAXj+lAHZ/ogBgkQCNlBE/coAAAEAUP9iATACygAHAAAFIxEzFSMRMwEw4OCKip4DaEj9KAAB' +
  'AAoAAAFrAsoAAwAAEwEjAWABC1f+9gLK/TYCygABABn/YgD5AsoABwAAFzMRIzUzESMZiorg4FYC2Ej8mAAAAQAmAQsCFgLP' +
  'AAYAABMTMxMjAwMm1DLqTrSgAQsBxP48AWf+mQAB//7/ZgG+/6YAAwAABSE1IQG+/kABwJpAAAEAKAJeAPEC/gALAAATHgIX' +
  'FSMuAic1kQshJQ87FzoxDAL+Fjc0EwwSOTkSCgACAC7/9gHgAiEAGwAmAAABMhYVESMnIwYGIyImNTQ2Nzc1NCYjIgYHJzY2' +
  'EwYGFRQWMzI2NTUBIGJeQBEEI01ESWB+g1s6NSpMIRsjYE5kTTcrRFoCIVZe/pNMLCpNUlBXBAMgQzQZEEITG/7iBDgzLSpL' +
  'TjAAAgBV//YCMAL4ABUAIQAAExQGBzM2NjMyFhUUBiMiJicjByMRMxMiBhUVFBYzMjY1NK0DAgUXUD9keXpjP1AXBxI/WJdV' +
  'QkFYSEcCPyI7ESIui4qKjC4gRAL4/uBiZwRjaWpkywAAAQA3//YBvwIiABoAAAUiJiY1NDY2MzIWFwcmJiMiFRQWMzI2NxUG' +
  'BgEsR28/QnFIKUwYGxhAHJ5NTCxDHBtBCjp6X2N8OhEMSQkQy2FnEg1ODg8AAgA3//YCEgL4ABUAIgAABSImNTQ2MzIWFzMm' +
  'JjU1MxEjJyMGBicyNjU1NCYjIgYVFBYBE2R4eWQ+TxkGAQVYRw0EGFAxVUVCWUdHRwqLioqNLiENMw/W/QhIIjBJXV4QZGtx' +
  'X2BqAAACADf/9gIBAiIAFwAeAAABMhYWFRUhFhYzMjY3FQYGIyImJjU0NjYXIgYHISYmASRFYzX+kQJZUDNPKilQN0x1QTtr' +
  'Rj9JBwERAT4CIjxtSTVbXxMSTRIRPntZWH5ESFFIRFUAAQAPAAABgwL9ABcAAAEjESMRIzU3NTQ2MzIWFwcmJiMiBhUVMwFM' +
  'h1heXlxSIDUTFxAqFiwrhwHU/iwB1CkeH2hbCwdFBQo7PyMAAAIAN/8QAhICIgAeACsAAAEyFhczNzMRFAYjIic1FjMyNjU1' +
  'NDY3IwYjIiY1NDYXIgYVFBYzMjY1NTQmARM1VR4FDEZ1e3ZLT3dFTwIBBDZwaHV1c0NKSUZRSkwCIigpR/3fc3QiUSpRRhUM' +
  'LQlRkoOAl0prY2NpV2EVbl8AAAEAVQAAAhkC+AAVAAATFAczNjYzMhYVESMRNCMiBhURIxEzrQUGGlk0YmJXeFpDWFgCGSgj' +
  'KSpdZ/6jAVeBZV7+6wL4AAACAE4AAAC1AuEACwAPAAATMhYVFAYjIiY1NDYXESMRghQfHxQWHh5BWALhGx0cHBwcHRvJ/egC' +
  'GAAAAv/J/xAAtQLhAAsAGwAAEzQ2MzIWFRQGIyImAyImJzUWFjMyNjURMxEUBk4eFhQfHxQWHjgZJg4PIBMgKlhIAqkdGxsd' +
  'HBwc/IMHBUcEBiMxAmv9mEtVAAEAVQAAAg0C+AATAAATFAYHMz4CNzczBxMjJwcVIxEzrAMBBAYYGQmrZ9noaro9V1cBaxA0' +
  'EwgeHwq15f7N+jXFAvgAAQBVAAAArQL4AAMAADMjETOtWFgC+AAAAQBVAAADVgIiACEAAAEyFhURIxE0IyIGFREjETQjIgYV' +
  'ESMRMxczNjYzMhczNjYCoVtaV21OQ1duUT5YRw0FGVUwfiYFG10CIl1o/qMBWX9aVv7YAVl/ZF7+6gIYSSopWi4sAAEAVQAA' +
  'AhkCIgATAAABMhYVESMRNCMiBhURIxEzFzM2NgFXYGJXeFlEWEcNBRpcAiJdaP6jAVeBZF7+6gIYSSopAAIAN//2AicCIgAN' +
  'ABkAAAEUBiMiJiY1NDYzMhYWBRQWMzI2NTQmIyIGAieHc0dvQIZzSW8//mtLUlFMTFJSSgENhZJBfVmFkEF7WV9vb19fbGwA' +
  'AAIAVf8QAjACIgAVACMAAAEyFhUUBiMiJicjFhYVFSMRMxczNjYXIgYHFRQWMzI2NjU0JgFUY3l5ZD5RFwYCBFhIDAQYTjFS' +
  'QwJBWDE/H0cCIoqLiY4vHxE0E9wDCEkjMEpcXhFjazZdPFxuAAIAN/8QAhICIgAVACIAAAU0NjcjBgYjIiY1NDYzMhYXMzcz' +
  'ESMDMjY3NTQmIyIGFRQWAboCAwYXUUBheXtiP1AYBA1GWJhTRQFEV0hGRwsSMBEiMIuKio0wI0n8+AEvW14SZmlxX19rAAAB' +
  'AFUAAAGOAiIAEwAAATIWFwcmJiMiBgYVESMRMxczNjYBTw8jDQsNHw4pSCtYSAoEGlICIgMDUQMELVE2/uICGGIsQAAAAQAz' +
  '//YBsgIiACkAACUUBiMiJic1FhYzMjY1NCYmJy4CNTQ2MzIWFwcmJiMiBhUUFhYXHgIBsnRiOFEfIFsvQzwWOTU0SihvWjFV' +
  'JR4iSic2ORo9MzNIJpROUBIQUBAbKyQUICAUFCg4LERKExFGDhQjHhYfHRQTKDkAAAEAEP/2AVMCkwAYAAAlMjY3FQYGIyIm' +
  'JjURIzU3NzMVMxUjERQWAQgUKg0ONBgqRyxMTSM0m5svPgcEQwcJHUhBATgqI3J7RP7KMS8AAAEAT//2AhUCGAATAAABESMn' +
  'IwYGIyImNREzERQzMjY1EQIVSA0EGlw0YWJZd1lFAhj96EcqJ11mAV/+p4BkXgEXAAEAAAAAAfwCGAAPAAAzAzMTHgIXMz4C' +
  'NxMzA8vLXnIIEg4DBAQPEwdyXswCGP7EFjYxEREyNhUBPP3oAAEACwABAwcCGQAiAAABJiYnIwYGBwMjAzMTFhYXMz4CNxMz' +
  'ExYWFzM2NjcTMwMjAa8NEwUEBBIOYGSTW0oLFAQEBAsOB19gXAsVBAQDFQxLWpVnAS8pTxYWTyr+0wIY/uIrWB0RMjcWAS7+' +
  '0iJQHRlYLgEe/egAAAEAEgAAAf8CGAALAAATAzMXNzMDEyMnByPUuWSKiWO5w2SSlGMBEgEGysr++v7u1tYAAQAB/xAB/gIY' +
  'ABoAABMzExYWFzM2NjcTMwMGBiMiJic1FhYzMjY3NwFedA8YBgQGGg5tX+ccWU4YJA0LHxEuORAcAhj+zyhJIRlRKQEw/Z5M' +
  'WgUDRgIENCtHAAABACcAAAGvAhgACQAAISE1ASE1IRUBIQGv/ngBIP7xAXD+5AEjOgGaREL+bgAAAQAc/2IBXALKAB0AAAUm' +
  'JjU1NCYjNTY2NTU0NjMVBgYVFRQHFRYVFRQWFwFcXGo/Ozs/blg0O21tOjWeAU5QkzMrSQEqMpRQTkgBLDGQZxMGE2eTMSsB' +
  'AAEA7/8PATgC+AADAAATMxEj70lJAvj8FwAAAQAg/2IBYALKAB0AABc2NjU1NDc1JjU1NCYnNRYWFRUUFjMVBgYVFRQGIyA0' +
  'O21tOjVcaj87Oz9uWFYCKzGRZxMGE2eSMSsBSAFOUJIzK0kBKjKVT08AAAEAMgEfAgkBogAXAAABJiYjIgYHNTYzMhYXFhYz' +
  'MjY3FQYjIiYBDSQvFhw+GDBIHTkuJC8VHT4YMUccOwE/EAsiGU41DBQQCyIZTTYNAAIASP9KAMQCIgALAA8AABMUBiMiJjU0' +
  'NjMyFgczEyPEJBoZJSUZGiRcOhlsAd4lHh4lJCAguP4AAAABAFv/9gHlAtQAIQAAARYWFwcmJiMiBhUUFjMyNjcVBgYHFSM1' +
  'LgI1NDY2NzUzAWEmRRkaGkIbUk1PTCxBHxs6J0M7VzAwWDpEAoQBEQtJChBlaGhfEQ1NDQ8CYWQJPHJZW3Q+CVQAAAEAIAAA' +
  'AhcC0wAgAAABMhYXByYmIyIGFRUzFSMVFAYHIRUhNTY2NTUjNTM1NDYBTjdYIh8eSSk5PMzMKhoBgP4JKzhgYG8C0xgRRg4Y' +
  'O0KLQmg9OxBQSgtAQmlClFlkAAIAOwCAAf8CQgAhADEAABM0NjcnNxc2NjMyFhc3FwcWFhUUBxcHJwYGIyInByc3JiY3FBYW' +
  'MzI2NjU0JiYjIgYGWhMQQjFCFzofHzcYQzBADxQjPy9DFzgfQDBCMEEQE0MiOyQlOiMjOiUkOyIBYR45F0QvQBESEhFAL0MX' +
  'OR8/MUIvQBASI0AvQhc5HyQ6IyM6JCU7IyM7AAABAA4AAAIsAsoAFgAAARMzAzMVIxUzFSMVIzUjNTM1IzUzAzMBHbNcyXyX' +
  'l5dWl5eXesddAW0BXf6JQFJAgYFAUkABdwAAAgDv/w8BOAL4AAMABwAAEzMRIxUzESPvSUlJSQL4/oPv/oMAAgA7//sBvwL9' +
  'ADMAQQAAEzQ2NyYmNTQ2MzIWFwcmJiMiBhUUFhcWFhUUBgcWFhUUBiMiJic1FhYzMjY1NCYmJy4CNxQWFxc2NjU0JiYnBgZD' +
  'MB8kKGZfOE4lGyJEMDwxOExNVi4dIydzZzdSICBeL0o4Ezc3NEsnSz9QFhcpG0Q+HCwBizI9DxQ3KDxFEw9DDhMfHBwnHBxI' +
  'PDNBERM1JkVMERBLDxorHBMcHxQUKjo2JTMeCA4rIhkoJRMHLgAAAgCVAncBrgLaAAsAFwAAEzQ2MzIWFRQGIyImNzQ2MzIW' +
  'FRQGIyImlRwTExwcExMcvBsTExwcExMbAqkaFxcaGRkZGRoXFxoZGRkAAAMAMf/2Aw8C1AATACYAPwAABSIuAjU0PgIzMh4C' +
  'FRQOAicyPgI1NC4CIyIGBhUUHgI3IiY1NDY2MzIXByYjIgYVFBYzMjY3FQYGAaBQhmM2NmOGUEyFZTk2Y4ZQQHBWMC5TcURa' +
  'jVAuU3JTY2IuWkFBOh0yKztBOUIXORkYMgo2Y4ZQUIZjNjZjhlBQhmM2NS5VckVBclYxUY1cQXJWMVp7ZUFlOR49GlRKTFMN' +
  'CkAKDgACACABfwE0AtIAGQAkAAATMhYVFSMnBgYjIiY1NDc3NTQmIyIGByc2NhcGBhUUFjMyNjU1sUFCLwwUOCYvOJ44Kh0c' +
  'MhcWGkE3PCodGTMtAtI2O9wqFRsxMmMGAhYhGg8LMQ0QtAIfGxkXLygXAAIAKAA4AdYB1wAGAA0AABM3FwcXByc3NxcHFwcn' +
  'KKg/jIw/qMaqPoyMPqoBDskkq6slyQ3JJKurJckAAAEAMgCAAggBhAAFAAABESM1ITUCCEf+cQGE/vy9RwD//wAoAOUBGgEz' +
  'AgYADgAAAAQAMf/2Aw8C1AATACYANAA9AAAFIi4CNTQ+AjMyHgIVFA4CJzI+AjU0LgIjIgYGFRQeAicRMzIWFRQGBxcjJyMV' +
  'NzI2NTQmIyMVAaBQhmM2NmOGUEyFZTk2Y4ZQQHBWMC5TcURajVAuU3JFgFJMMB50VmQ+MicsKCwxCjZjhlBQhmM2NmOGUFCG' +
  'YzY1LlVyRUFyVjFRjVxBclYxXwG1QEEvNwzCra3rKB8jIIoAAAH//QL4AfcDOgADAAABITUhAff+BgH6AvhCAAACADcBoQF1' +
  'AtQACwAXAAATIiY1NDYzMhYVFAYnMjY1NCYjIgYVFBbWSFdWSUdYWEYwLS8uMS4uAaFVRERWVkREVTs0Kiw0NCwqNAAAAgAy' +
  'AAACCQJWAAsADwAAATMVIxUjNSM1MzUzATUhFQFBx8dIx8dI/vEB1wGHR87OR8/9qkdHAAABABgBoAEzA1UAGQAAASE1Nz4C' +
  'NTQmIyIGByc2NjMyFhUUBgcHMwEy/uZzKSkPJR4eMRojHUUrQEk7OFHDAaA2cCcxJxYgIBcULhkePzcxTjVNAAABABEBmAFB' +
  'A1UAKAAAEzIWFRQGBxUWFhUUBiMiJic1FjMyNjU0JiMjNTMyNjU0JiMiBgcnNjalR0grHicvVFklQB5GPjQwOjQ5OTIvKR0f' +
  'NRskH0UDVT4wKDQKAwczKTpJDQ8/IikjJCE3Jx8gHRURLhcaAAEAKAJeAPEC/gALAAATDgIHIzU+Ajcz8QwyORg6DyMiC2oC' +
  '9BI5ORIMEzQ3FgABAFX/EAIaAhgAGQAAAREjJyMGBiMiJicjFhYVFSMRMxEUMzI2NRECGkcOBRlQOCc4FAQCA1hYeFlEAhj9' +
  '6EgoKhkUEjwpnAMI/qZ/ZF4BFwAAAQA3/4ECJQL4ABIAAAUjESMRIxEGBiMiJiY1NDY2MyECJTpmOg8nET5cMzdkQQESfwM/' +
  '/MEBkAQFLmxbYG0u//8ASAEdAMQBpAIHAA8AAAErAAEADv8QANQAAAAUAAAXFAYjIic1FhYzMjY1NCYnNzMHFhbUSkogEgke' +
  'DiQmNSYrOhokM4swNQU3AgMTGRoYBVY1CCgAAQAlAaAA8ANMAAwAABMRIxE0NjcGBgcHJzfwRwMBChgNNiOCA0z+VAEUGioV' +
  'CRUJJzFcAAIAIAF/AVkC0gALABcAAAEUBiMiJjU0NjMyFgcUFjMyNjU0JiMiBgFZVkhDWFRJR1X6LDExLCwxMSwCKVFZV1NS' +
  'V1ZTOjs7Ojs5OQACACcAOAHVAdcABgANAAABByc3JzcXBwcnNyc3FwHVqj6MjD6qx6k+jIw+qQEBySWrqyTJDcklq6skyQAE' +
  'ACIAAALgAsoAAwAQABsAJAAAMwEzAQM0NjcGBgcHJzczESMBNSM1EzMRMxUjFSczNTQ2NwYGB34BtEv+TCMDAQoYDTYjgklH' +
  'AbLDxUk9Pch9AgEFIAsCyv02AjIaKhUJFQknMVz+VP7iYDQBG/7tPGCcXRU4GAsxEQAAAwAWAAAC2ALKAAMAEAAqAAAzATMB' +
  'AzQ2NwYGBwcnNzMRIwE1Nz4CNTQmIyIGByc2NjMyFhUUBgcHMxVgAbRL/kwRAwEKGA02I4JJRwEjcykpDyUeHjEaIx1FK0BJ' +
  'OzhRwwLK/TYCMhoqFQkVCScxXP5U/uI2cCcxJxYgIBcULhkePzcxTjVNPgAABAAPAAADBALTACgALAA3AEAAABMiJic1FjMy' +
  'NjU0JiMjNTMyNjU0JiMiBgcnNjYzMhYVFAYHFRYWFRQGAwEzASE1IzUTMxEzFSMVJzM1NDY3BgYHkiVAHkY+NDA6NDk5Mi8p' +
  'HR81GyQfRS5HSCseJy9UQQG0S/5MAYfDxUk9Pch9AgEFIAsBFg0PPyIpIyQhNycfIB0VES4XGj4wKDQKAwczKTpJ/uoCyv02' +
  'YDQBG/7tPGCcXRU4GAsxEQACABj/QAGkAiIACwArAAABFAYjIiY1NDYzMhYHFAYGBw4CFRQWMzI2NxcGBiMiJjU0NjY3PgI1' +
  'NTMBOyMbGSQkGRsjFw8kISYsEj86MkwiHyhhPF9oHTUkIiIMRgHeJR4eJSQgINIlODEcIC0qHjA0GhBGFRxeUS0/NR4dKSoc' +
  'EQD//wAAAAACfgOwAiYAIgAAAAcAQQCUALL//wAAAAACfgOwAiYAIgAAAAcAdADhALL//wAAAAACfgOwAiYAIgAAAAcAwABt' +
  'ALL//wAAAAACfgORAiYAIgAAAAcAwgBfALL//wAAAAACfgOMAiYAIgAAAAcAaAAdALL//wAAAAACfgNuAiYAIgAAAAcAwQCo' +
  'AD0AAv//AAADNQLKAA8AEwAAISE1IwcjASEVIRUhFSEVISUzESMDNf6M+mtdAVMB4/7mAQf++QEa/bXXOt3dAspP307/3gFN' +
  '//8APf8QAlkC1AImACQAAAAHAHgBBQAA//8AYQAAAfADsAImACYAAAAHAEEAhwCy//8AYQAAAfADsAImACYAAAAHAHQA1ACy' +
  '//8AYQAAAfADsAImACYAAAAHAMAAYACy//8AYQAAAfADjAImACYAAAAHAGgAEACy//8AKAAAASoDsAImACoAAAAHAEEAAACy' +
  '//8AKAAAAT4DsAImACoAAAAHAHQATQCy//8AAQAAAVMDsAImACoAAAAHAMD/2QCy//8AHgAAATcDjAImACoAAAAHAGj/iQCy' +
  'AAIAHgAAAp0CygANABkAAAEyFhYVFAYjIxEjNTMRFyMVMxUjFTMgETQmAT1rnlfFsb9KSshusrJaASKOAspQm3O1twE6TgFC' +
  'TfVO7QEcj4X//wBhAAAClwORAiYALwAAAAcAwgCdALL//wA9//YC0AOwAiYAMAAAAAcAQQDdALL//wA9//YC0AOwAiYAMAAA' +
  'AAcAdAEqALL//wA9//YC0AOwAiYAMAAAAAcAwAC2ALL//wA9//YC0AORAiYAMAAAAAcAwgCoALL//wA9//YC0AOMAiYAMAAA' +
  'AAcAaABmALIAAQBAAIQB+gI+AAsAAAEXBxcHJwcnNyc3FwHIMqqpMqunNKmqNKkCPjOqqjOpqTOqqTSrAAMAPf/hAtAC6gAX' +
  'ACAAKQAAARQGBiMiJwcnNyYmNTQ2NjMyFhc3FwcWBRQWFwEmIyIGBTQnARYWMzI2AtBLkmxwSTA9NCwsSJNwNFklLj0zXv3M' +
  'FxgBPzROeXMB1TP+wBpFKnpwAWZvpVwvRChKMYxXbqRcGBVCKUdjsT1kJQHDI5mHgUn+OhIUmwD//wBa//YCgAOwAiYANgAA' +
  'AAcAQQDEALL//wBa//YCgAOwAiYANgAAAAcAdAERALL//wBa//YCgAOwAiYANgAAAAcAwACdALL//wBa//YCgAOMAiYANgAA' +
  'AAcAaABNALL//wAAAAACNgOwAiYAOgAAAAcAdAC+ALIAAgBhAAACKgLKAA0AFgAAARQGBiMjFSMRMxUzMhYFMjY1NCYjIxEC' +
  'KjR9bVFaWmCRfv7ZaWFXYlkBfjxnQJsCynxu+UNPRUP+5gABAFX/9gJKAv0ANgAAARQOAxUUFhYXFhYVFAYjIiYnNRYWMzI2' +
  'NTQmJyYmNTQ+AzU0JiMiBgYVESMRNDY2MzIWAgocKiocDSYlNj5nUy9IGhpMKDcwKTU/LhspKRtHOCM9JVg6ZD9hdwJpIjMn' +
  'IB8SDRYdGSRLO1VOEhBPEBouKCQyIik7KB8sISAmGyomEy4r/bgCSENPI0r//wAu//YB4AL+AiYAQgAAAAYAQW8A//8ALv/2' +
  'AeAC/gImAEIAAAAHAHQAvAAA//8ALv/2AeAC/gImAEIAAAAGAMBIAP//AC7/9gHgAt8CJgBCAAAABgDCOgD//wAu//YB4ALa' +
  'AiYAQgAAAAYAaPgA//8ALv/2AeADMQImAEIAAAAHAMEAgwAAAAMALv/2Ay0CIgAsADMAPgAAATIWFhUVIRYWMzI2NxUGBiMi' +
  'JwYGIyImNTQ2Nzc1NCYjIgYHJzY2MzIWFzY2FyIGBzM0JgUGBhUUFjMyNjU1AltBXjP+qQJPSjJMJihNMo0+IlxNSWF4fFo9' +
  'MyhNIRsjZDE+URUaVDU6QwX4Of6YXkgzKj9VAiI8bEg2YFsTEk0SEXE0PU1SUFcEAyJBNBgRQhQaKS0pLkhPSkVU1wQ4My0q' +
  'S04wAP//ADf/EAG/AiICJgBEAAAABwB4AKoAAP//ADf/9gIBAv4CJgBGAAAABgBBcwD//wA3//YCAQL+AiYARgAAAAcAdADA' +
  'AAD//wA3//YCAQL+AiYARgAAAAYAwEwA//8AN//2AgEC2gImAEYAAAAGAGj8AP////8AAADIAv4CJgDLAAAABgBB1wD//wBM' +
  'AAABFQL+AiYAywAAAAYAdCQA////2AAAASoC/gImAMsAAAAGAMCwAP////UAAAEOAtoCJgDLAAAABwBo/2AAAAACADf/9gIn' +
  'Av0AIAAsAAATFhYXNxcHFhYVFAYjIiYmNTQ2MzIWFzcmJicHJzcmJicTIgYVFBYzMjY1NCbYIEEdcyZjRFeGdEhvP39sNU8Y' +
  'BBBCKoImcBUuF3tUS0xTU0xOAv0PJBVDNjlAvHqOjzttS3CAHB4COWAmSzdADhsM/tFZU0lfYVw+Wf//AFUAAAIZAt8CJgBP' +
  'AAAABgDCVgD//wA3//YCJwL+AiYAUAAAAAcAQQCFAAD//wA3//YCJwL+AiYAUAAAAAcAdADSAAD//wA3//YCJwL+AiYAUAAA' +
  'AAYAwF4A//8AN//2AicC3wImAFAAAAAGAMJQAP//ADf/9gInAtoCJgBQAAAABgBoDgAAAwAyAHkCCQJHAAsADwAbAAABIiY1' +
  'NDYzMhYVFAYFNSEVByImNTQ2MzIWFRQGAR0XISEXFyAg/v4B1+wXISEXFyAgAc4dICIaGiIgHZFHR8QdICIaGiIgHQAAAwA3' +
  '/98CJwI2ABUAHgAmAAABFAYjIicHJzcmJjU0NjMyFzcXBxYWBRQWFxMmIyIGBTQnAxYzMjYCJ4dzSTgoOi0fIYZzSTonOy0d' +
  'Iv5rCw3cJDRSSgE6F9wiNFFMAQ2FkiE4Jz4kZUCFkCQ4Jj8jYz4mQRkBMhlsX0ox/s4Xb///AE//9gIVAv4CJgBWAAAABwBB' +
  'AIsAAP//AE//9gIVAv4CJgBWAAAABwB0ANgAAP//AE//9gIVAv4CJgBWAAAABgDAZAD//wBP//YCFQLaAiYAVgAAAAYAaBQA' +
  '//8AAf8QAf4C/gImAFoAAAAHAHQAogAAAAIAVf8QAjAC+AAZACYAAAEUBiMiJicjHgIVFSMRMxUUBgczNjYzMhYHNCYjIgYH' +
  'FRQWMzI2AjB5Yz9QGAYBAwJYWAIBBBhOQGN5W0ZKUkQCQVhKRQENiY4uIAcgIgvgA+jgDi0NIjCMiGVlXFwTY2tr//8AAf8Q' +
  'Af4C2gImAFoAAAAGAGjeAAABACgCXgF6Av4AEgAAEx4CFxUjJiYnBgYHIzU+Ajf9DC0xEz4aOBsbNho8Ey8sDQL+Fjc1EwsQ' +
  'LxsbLhELFDQ3FgACACgCXgEEAzEACwAXAAATIiY1NDYzMhYVFAYnMjY1NCYjIgYVFBaVMTw8MS9APzAZHyAYGCAdAl44MjI3' +
  'NzEzODIeGhoeHhoaHgAAAQAoAl4BlwLfABUAABM2NjMyFhYzMjY3MwYGIyImJiMiBgcoBjkvHjUwFRcZBzIGOC8cNTEWGBgH' +
  'Al47RR0cHR06RhwdHR0AAQAoAOUBzAEzAAMAADc1IRUoAaTlTk4AAQAoAOUDwAEzAAMAADc1IRUoA5jlTk4AAQAMAdUAowLK' +
  'AAkAABM2NjczDgIHIwwOMBhBCRQQBV8B4DWANSZXVSMAAQAMAdUAowLKAAkAABMGBgcjPgI3M6MNMRhBChMQBV4CvzSBNSZX' +
  'VSP//wAf/38AtgB0AAcAxgAT/aoAAQAMAdUApALKAAkAABMeAhcjJiYnN3IFEBQJQRkwDgcCyiNVVyY1gTQLAAACAAwB1QFb' +
  'AsoACAARAAABBgYHIyc2NjcjBgYHIyc2NjcBWw4cCF8HDjAZeA4cCF4GDi8ZAso6hzQLNX82Ooc0CzV/NgAAAgAMAdUBWwLK' +
  'AAkAEwAAAQYGByM+AjczBwYGByM+AjczAVsNMRhCChMRBV6yDTEYQAoSEAVeAr81gDUmV1UjCzWANSZXVSMAAQBVAAAArQIY' +
  'AAMAADMjETOtWFgCGAAAAQAyAT0CCAGEAAMAAAEVITUCCP4qAYRHRwABAAAAzQEEABgAZgAGAAEAAAAAAAAAAAAAAAAABAAB' +
  'AAAAAAAAAB0AMwBjAK4A9wFJAVcBcQGMAasBwAHUAeAB9gIGAjACSQJ1ArMC2AMJA0oDXAOtA+8EFQQ6BE0EYARzBLMFHwVD' +
  'BXgFowXDBdoF7gYgBjcGTwZsBokGmAa+Bt8HDAcvB2IHiwfJB9oH+QgWCFAIawiBCJgIqQi4CMkI3AjpCQAJOwluCZgJzAn+' +
  'CiQKYwqGCqMKzwrxCv0LLwtQC3oLsAvlDAgMRgxtDI4MrAzoDQENLw1GDXINfw2rDdIN0g3vDiMOUw6gDsMO1Q81D1sPtA/r' +
  'EAkQGRAhEHgQhhCsEMgQ8hEsEUMRbBGMEZURtxHREfcSFRJTEpgS9hM3E0MTTxNbE2cTcxN/E6ITrhO6E8YT0hPeE+oT9hQC' +
  'FA4UNhRCFE4UWhRmFHIUfhSYFN4U6hT2FQIVDhUaFT8VjBWXFaMVrhW5FcQV0BYsFjgWQxZPFloWZRZwFnsWhhaSFtcW4hbu' +
  'FvoXBRcQFxsXSBeIF5QXoBerF7YXwhf7GAYYJxhNGHEYfRiJGJ4Ysxi8GNIY9RkZGSUZMgABAAAAAgPXorjeyV8PPPUABwPo' +
  'AAAAAN2A0+cAAAAA42PAt/2T/nsK8AQrAAAABgACAAAAAAAAAlgAXgEEAAABDQBIAZgAQQKGABkCPAA+Az8AMQLcADUA4QBB' +
  'ASwAKAEsAB4CJwApAjwAMgEMACkBQgAoAQwASAF0AAoCPAAxAjwAWQI8ADACPAAtAjwAFQI8AD8CPAA3AjwALAI8ADECPAAy' +
  'AQwASAEMAB8CPAAyAjwAOAI8ADIBsgAMA4MAOgJ/AAACigBhAngAPQLaAGECLABhAgcAYQLYAD0C5QBhAVMAKAER/7ICawBh' +
  'AgwAYQOLAGEC+ABhAw0APQJdAGEDDQA9Am4AYQIlADMCLAAKAtsAWgJYAAADogAMAkoABAI2AAACPAAmAUkAUAF0AAoBSQAZ' +
  'AjwAJgG8//4BGQAoAjEALgJnAFUB4AA3AmcANwI0ADcBWAAPAmcANwJqAFUBAgBOAQL/yQIWAFUBAgBVA6cAVQJqAFUCXQA3' +
  'AmcAVQJnADcBnQBVAd8AMwFpABACagBPAfwAAAMSAAsCEQASAf4AAQHWACcBfAAcAicA7wF8ACACPAAyAQQAAAENAEgCPABb' +
  'AjwAIAI8ADsCPAAOAicA7wIBADsCRACVA0AAMQFlACAB/QAoAjwAMgFCACgDQAAxAfT//QGsADcCPAAyAV4AGAFeABEBGQAo' +
  'Am8AVQKPADcBDABIAOEADgFeACUBeAAgAf0AJwLpACIDAwAWAw0ADwGyABgCfwAAAn8AAAJ/AAACfwAAAn8AAAJ/AAADcf//' +
  'AngAPQIsAGECLABhAiwAYQIsAGEBUwAoAVMAKAFTAAEBUwAeAtoAHgL4AGEDDQA9Aw0APQMNAD0DDQA9Aw0APQI8AEADDQA9' +
  'AtsAWgLbAFoC2wBaAtsAWgI2AAACXQBhAncAVQIxAC4CMQAuAjEALgIxAC4CMQAuAjEALgNgAC4B4AA3AjQANwI0ADcCNAA3' +
  'AjQANwEC//8BAgBMAQL/2AEC//UCXQA3AmoAVQJdADcCXQA3Al0ANwJdADcCXQA3AjwAMgJdADcCagBPAmoATwJqAE8CagBP' +
  'Af4AAQJnAFUB/gABAaIAKAEsACgBvwAoAfQAKAPoACgArwAMAK8ADAD6AB8ArwAMAWcADAFnAAwBAgBVAjwAMgABAAAELf7b' +
  'AAALGP2T/ZQK8APoAAAAAAAAAAAAAAAAAAAAzQAEAkEBkAAFAAACigJYAAAASwKKAlgAAAFeADIBQgAAAgsFAgQFBAICBIAA' +
  'AAMAAAAAAAAAAAAAAABHT09HAMAAICISBC3+2wAABGQBiwAAAAEAAAAAAhgCygAAACAABAAAAAIAAAADAAAAFAADAAEAAAAU' +
  'AAQAQAAAAAwACAACAAQAfgD/IBQgHSIS//8AAAAgAKAgEyAYIhL////h/8DgsOCt3roAAQAAAAAAAAAAAAAAAAAAAAcAWgAD' +
  'AAEECQAAALYAAAADAAEECQABABIAtgADAAEECQACAA4AyAADAAEECQADADYA1gADAAEECQAEACIBDAADAAEECQAFAFQBLgAD' +
  'AAEECQAGACABggBDAG8AcAB5AHIAaQBnAGgAdAAgADIAMAAyADIAIABUAGgAZQAgAE4AbwB0AG8AIABQAHIAbwBqAGUAYwB0' +
  'ACAAQQB1AHQAaABvAHIAcwAgACgAaAB0AHQAcABzADoALwAvAGcAaQB0AGgAdQBiAC4AYwBvAG0ALwBuAG8AdABvAGYAbwBu' +
  'AHQAcwAvAGwAYQB0AGkAbgAtAGcAcgBlAGUAawAtAGMAeQByAGkAbABsAGkAYwApAE4AbwB0AG8AIABTAGEAbgBzAFIAZQBn' +
  'AHUAbABhAHIAMgAuADAAMQA1ADsARwBPAE8ARwA7AE4AbwB0AG8AUwBhAG4AcwAtAFIAZQBnAHUAbABhAHIATgBvAHQAbwAg' +
  'AFMAYQBuAHMAIABSAGUAZwB1AGwAYQByAFYAZQByAHMAaQBvAG4AIAAyAC4AMAAxADUAOwAgAHQAdABmAGEAdQB0AG8AaABp' +
  'AG4AdAAgACgAdgAxAC4AOAAuADQALgA3AC0ANQBkADUAYgApAE4AbwB0AG8AUwBhAG4AcwAtAFIAZQBnAHUAbABhAHIAAwAA' +
  'AAAAAP+cADIAAAAAAAAAAAAAAAAAAAAAAAAAAA==';

/** The typeface's bytes, decoded once and held, since every label read after the
 * first reads the same font. */
let decoded: Uint8Array | undefined;

/** The shipped typeface's bytes. */
export function fontBytes(): Uint8Array {
  if (decoded) return decoded;
  const binary = atob(ENCODED);
  const bytes = new Uint8Array(binary.length);
  for (let at = 0; at < binary.length; at += 1) bytes[at] = binary.charCodeAt(at);
  decoded = bytes;
  return decoded;
}
